<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle\VehicleAddon;
use App\Models\Service\ServiceType;
use Carbon\Carbon;

class VehicleAddonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->seedVehicleAddons();
    }

    /**
     * Seed vehicle addons for different service types
     */
    private function seedVehicleAddons(): void
    {
        // Get service types
        $serviceTypes = ServiceType::all()->keyBy('code');

        $addons = [
            // ========== Universal addons (available for all service types) ==========
            [
                'service_type_id' => null, // Universal
                'name' => 'GPS Navigation System',
                'description' => 'Professional GPS navigation system for easy route guidance',
                'addon_type' => 'item',
                'pricing_type' => 'per_day',
                'quantity_unit' => 'pieces',
                'amount' => 500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'always',
                'sort_order' => 1,
                'icon' => 'gps_fixed',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => null,
                'name' => 'Child Safety Seat',
                'description' => 'Safety-certified child seat for children under 12 years',
                'addon_type' => 'item',
                'pricing_type' => 'per_day',
                'quantity_unit' => 'pieces',
                'amount' => 750.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 3,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'always',
                'sort_order' => 2,
                'icon' => 'child_care',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => null,
                'name' => 'Baby Car Seat',
                'description' => 'Infant car seat for babies under 2 years',
                'addon_type' => 'item',
                'pricing_type' => 'per_day',
                'quantity_unit' => 'pieces',
                'amount' => 1000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 2,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'always',
                'sort_order' => 3,
                'icon' => 'child_friendly',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => null,
                'name' => 'Mobile Charger',
                'description' => 'Universal mobile phone charger with multiple ports',
                'addon_type' => 'item',
                'pricing_type' => 'per_day',
                'quantity_unit' => 'pieces',
                'amount' => 250.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 2,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'always',
                'sort_order' => 4,
                'icon' => 'battery_charging_full',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => null,
                'name' => 'Wi-Fi Hotspot',
                'description' => 'Mobile Wi-Fi hotspot for internet connectivity during travel',
                'addon_type' => 'item',
                'pricing_type' => 'per_day',
                'quantity_unit' => 'pieces',
                'amount' => 800.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'always',
                'sort_order' => 5,
                'icon' => 'wifi',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => null,
                'name' => 'Extra Driver',
                'description' => 'Additional qualified driver for long journeys',
                'addon_type' => 'service',
                'pricing_type' => 'per_day',
                'quantity_unit' => 'pieces',
                'amount' => 2500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'always',
                'sort_order' => 6,
                'icon' => 'person_add',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],

            // ========== Wedding specific addons ==========
            [
                'service_type_id' => $serviceTypes['wedding_hire']->id ?? null,
                'name' => 'Wedding Decoration Package',
                'description' => 'Complete vehicle decoration with flowers, ribbons, and wedding themes',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 5000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 10,
                'icon' => 'celebration',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['wedding_hire']->id ?? null,
                'name' => 'Bridal Car Ribbon Set',
                'description' => 'Elegant ribbon decoration set for bridal car',
                'addon_type' => 'item',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 1500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 2,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 11,
                'icon' => 'redeem',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['wedding_hire']->id ?? null,
                'name' => 'Fresh Flower Arrangement',
                'description' => 'Beautiful fresh flower arrangements for wedding vehicles',
                'addon_type' => 'item',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 3500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 3,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 12,
                'icon' => 'local_florist',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['wedding_hire']->id ?? null,
                'name' => 'Wedding Photographer Seat',
                'description' => 'Reserved comfortable seat for wedding photographer in vehicle',
                'addon_type' => 'service',
                'pricing_type' => 'per_hour',
                'quantity_unit' => 'hours',
                'amount' => 1000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_hour',
                'min_qty' => 1,
                'max_qty' => 8,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 13,
                'icon' => 'photo_camera',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],

            // ========== Self-driven / Ride Now specific addons ==========
            [
                'service_type_id' => $serviceTypes['ride_now']->id ?? null,
                'name' => 'Comprehensive Insurance',
                'description' => 'Full coverage insurance for self-driven vehicles',
                'addon_type' => 'insurance',
                'pricing_type' => 'percentage',
                'quantity_unit' => 'pieces',
                'amount' => 15.00,
                'rate_type' => 'percentage',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 20,
                'icon' => 'security',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['ride_now']->id ?? null,
                'name' => 'Basic Insurance',
                'description' => 'Basic insurance coverage for self-driven vehicles',
                'addon_type' => 'insurance',
                'pricing_type' => 'percentage',
                'quantity_unit' => 'pieces',
                'amount' => 8.00,
                'rate_type' => 'percentage',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 21,
                'icon' => 'verified_user',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['ride_now']->id ?? null,
                'name' => 'Emergency Roadside Assistance',
                'description' => '24/7 emergency roadside assistance and breakdown support',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 1500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 22,
                'icon' => 'build',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['ride_now']->id ?? null,
                'name' => 'Fuel Package',
                'description' => 'Pre-paid fuel package for convenience',
                'addon_type' => 'item',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 5000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 23,
                'icon' => 'local_gas_station',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],

            // ========== Corporate service addons ==========
            [
                'service_type_id' => $serviceTypes['corporate']->id ?? null,
                'name' => 'Corporate Branding',
                'description' => 'Custom corporate branding and signage on vehicle',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 2000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 30,
                'icon' => 'business',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['corporate']->id ?? null,
                'name' => 'Business Meeting Setup',
                'description' => 'Mobile office setup with table and power outlets',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 1500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 31,
                'icon' => 'meeting_room',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['corporate']->id ?? null,
                'name' => 'VIP Escort Service',
                'description' => 'Professional escort and security service for VIP clients',
                'addon_type' => 'service',
                'pricing_type' => 'per_day',
                'quantity_unit' => 'pieces',
                'amount' => 5000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_day',
                'min_qty' => 1,
                'max_qty' => 2,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 32,
                'icon' => 'shield',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],

            // ========== Airport service addons ==========
            [
                'service_type_id' => $serviceTypes['airport_transfer']->id ?? null,
                'name' => 'Meet & Greet Service',
                'description' => 'Professional meet and greet service at airport arrival',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 1500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 40,
                'icon' => 'waving_hand',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['airport_transfer']->id ?? null,
                'name' => 'Flight Tracking',
                'description' => 'Real-time flight tracking and schedule adjustment',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 41,
                'icon' => 'flight',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['airport_transfer']->id ?? null,
                'name' => 'Luggage Assistance',
                'description' => 'Professional luggage handling and assistance',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 800.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 42,
                'icon' => 'luggage',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['airport_transfer']->id ?? null,
                'name' => 'Multi-Stop Package',
                'description' => 'Additional charge for multiple stop transfers',
                'addon_type' => 'fee',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 5,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 43,
                'icon' => 'add_location',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['airport_transfer']->id ?? null,
                'name' => 'Express Transfer',
                'description' => 'Premium express transfer service with priority routing',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 1000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 44,
                'icon' => 'speed',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],

            // ========== Break down service addons ==========
            [
                'service_type_id' => $serviceTypes['break_down_service']->id ?? null,
                'name' => 'Emergency Towing',
                'description' => 'Emergency vehicle towing service (per km)',
                'addon_type' => 'service',
                'pricing_type' => 'per_km',
                'quantity_unit' => 'km',
                'amount' => 150.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 100,
                'threshold_quantity' => 10,
                'threshold_price' => 100.00,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 50,
                'icon' => 'local_shipping',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['break_down_service']->id ?? null,
                'name' => 'On-Site Repair',
                'description' => 'Basic on-site vehicle repair service',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 2000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 51,
                'icon' => 'handyman',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['break_down_service']->id ?? null,
                'name' => 'Jump Start Service',
                'description' => 'Battery jump start service',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 1000.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 1,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 52,
                'icon' => 'battery_alert',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
            [
                'service_type_id' => $serviceTypes['break_down_service']->id ?? null,
                'name' => 'Tire Change Service',
                'description' => 'Professional tire changing service',
                'addon_type' => 'service',
                'pricing_type' => 'fixed',
                'quantity_unit' => 'pieces',
                'amount' => 1500.00,
                'rate_type' => 'flat',
                'billing_type' => 'per_package',
                'min_qty' => 1,
                'max_qty' => 4,
                'is_active' => true,
                'is_mandatory' => false,
                'is_optional' => true,
                'is_taxable' => false,
                'availability_type' => 'service_specific',
                'sort_order' => 53,
                'icon' => 'tire_repair',
                'valid_from' => Carbon::now(),
                'valid_to' => null,
            ],
        ];

        // Create or update addons
        foreach ($addons as $addonData) {
            VehicleAddon::updateOrCreate(
                [
                    'service_type_id' => $addonData['service_type_id'],
                    'name' => $addonData['name'],
                ],
                $addonData
            );
        }

        $this->command->info('Vehicle addons seeded successfully!');
    }
}