<?php
namespace App\Services\Hr;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
class HrDataQualityService{
public function summarize(string$companyId):array{$issues=[];
$this->metric($issues,'active_staff_without_user','identity','critical',Schema::hasTable('staff')?(int)DB::table('staff as s')->leftJoin('users as u','u.id','=','s.user_id')->where('s.company_id',$companyId)->whereNull('s.employment_ended_at')->whereNull('s.deleted_at')->whereNull('u.id')->count():null);
$this->metric($issues,'active_staff_without_employee_number','people','high',Schema::hasTable('staff')?(int)DB::table('staff')->where('company_id',$companyId)->whereNull('employment_ended_at')->whereNull('deleted_at')->whereNull('code')->count():null);
$this->metric($issues,'active_staff_without_profile_version','people','medium',Schema::hasTable('hr_staff_profile_versions')?(int)DB::table('staff as s')->where('s.company_id',$companyId)->whereNull('s.employment_ended_at')->whereNull('s.deleted_at')->whereNotExists(fn($q)=>$q->selectRaw('1')->from('hr_staff_profile_versions as p')->whereColumn('p.staff_id','s.id'))->count():null);
$this->metric($issues,'active_staff_without_assignment','people','high',Schema::hasTable('hr_employment_assignments')?(int)DB::table('staff as s')->where('s.company_id',$companyId)->whereNull('s.employment_ended_at')->whereNull('s.deleted_at')->whereNotExists(fn($q)=>$q->selectRaw('1')->from('hr_employment_assignments as a')->whereColumn('a.staff_id','s.id')->whereDate('a.effective_from','<=',now())->where(fn($x)=>$x->whereNull('a.effective_until')->orWhereDate('a.effective_until','>=',now())))->count():null);
$this->metric($issues,'attendance_mapping_missing','attendance','high',Schema::hasTable('hr_attendance_person_mappings')?(int)DB::table('staff as s')->where('s.company_id',$companyId)->whereNull('s.employment_ended_at')->whereNull('s.deleted_at')->whereNotExists(fn($q)=>$q->selectRaw('1')->from('hr_attendance_person_mappings as m')->whereColumn('m.staff_id','s.id')->where('m.enrollment_status','verified')->whereDate('m.effective_from','<=',now())->where(fn($x)=>$x->whereNull('m.effective_until')->orWhereDate('m.effective_until','>=',now())))->count():null);
$this->metric($issues,'attendance_quarantine_open','attendance','high',Schema::hasTable('hr_attendance_quarantine_items')?(int)DB::table('hr_attendance_quarantine_items')->where('company_id',$companyId)->where('status','open')->count():null);
$this->metric($issues,'attendance_exceptions_open','attendance','medium',Schema::hasTable('hr_attendance_exceptions')?(int)DB::table('hr_attendance_exceptions')->where('company_id',$companyId)->where('status','open')->count():null);
$this->metric($issues,'expired_employee_records','documents','medium',Schema::hasTable('hr_employee_records')?(int)DB::table('hr_employee_records as r')->join('staff as s','s.id','=','r.staff_id')->where('s.company_id',$companyId)->whereNotNull('r.expiry_date')->whereDate('r.expiry_date','<',now())->count():null);
$this->metric($issues,'evidence_retention_due','documents','medium',Schema::hasTable('domain_evidence_files')?(int)DB::table('domain_evidence_files')->where('domain','hr')->where('company_id',$companyId)->whereNull('deleted_at')->whereNotNull('retention_until')->where('retention_until','<',now())->count():null);
$this->metric($issues,'pending_payment_method_changes','payroll_readiness','high',Schema::hasTable('staff_payment_method_changes')?(int)DB::table('staff_payment_method_changes as c')->join('staff as s','s.id','=','c.staff_id')->where('s.company_id',$companyId)->where('c.status','pending')->count():null);
$this->metric($issues,'unapproved_payroll_input_facts','payroll_readiness','critical',Schema::hasTable('hr_payroll_input_facts')?(int)DB::table('hr_payroll_input_facts')->where('company_id',$companyId)->whereIn('status',['staged','rejected'])->count():null);
$available=collect($issues)->where('available',true);return['issues'=>$issues,'totals'=>['critical'=>$available->where('severity','critical')->sum('count'),'high'=>$available->where('severity','high')->sum('count'),'medium'=>$available->where('severity','medium')->sum('count'),'unavailable_checks'=>collect($issues)->where('available',false)->count()],'generated_at'=>now()->toIso8601String()];}
private function metric(array&$issues,string$code,string$domain,string$severity,?int$count):void{$issues[]=['code'=>$code,'domain'=>$domain,'severity'=>$severity,'available'=>$count!==null,'count'=>$count,'detail_permission'=>$this->permission($domain)];}private function permission(string$domain):string{return match($domain){'identity','people'=>'hr.people.view-all','attendance'=>'hr.attendance.results.view','documents'=>'hr.people.timeline-confidential','payroll_readiness'=>'hr.payroll-inputs.view',default=>'hr.analytics.view'};}}
