<?php
namespace App\Services\Hr;use Barryvdh\DomPDF\Facade\Pdf;use RuntimeException;use ZipArchive;
/**
 * HR reporting: artifact *rendering*. Given the dataset built by
 * {@see HrReportDatasetService}, serializes it to the requested output
 * format (csv/pdf/xlsx) and returns the raw file content plus its
 * extension/mime type, ready for the caller (the generation job) to store
 * as the run's downloadable artifact. Stateless — no DB access, no
 * retention/storage concerns; those belong to the job that calls this
 * service, not this class itself.
 */
class HrReportArtifactService{
public function render(string$format,array$columns,array$rows,string$title):array{return match($format){'csv'=>$this->csv($columns,$rows),'pdf'=>$this->pdf($columns,$rows,$title),'xlsx'=>$this->xlsx($columns,$rows),default=>throw new RuntimeException('Unsupported HR report format.')};}
private function csv(array$c,array$r):array{$h=fopen('php://temp','w+b');fputcsv($h,$c);foreach($r as$row)fputcsv($h,array_map(fn($key)=>$this->scalar($row[$key]??null),$c));rewind($h);$body=stream_get_contents($h);fclose($h);return['content'=>$body,'extension'=>'csv','mime'=>'text/csv'];}
private function pdf(array$c,array$r,string$title):array{$body=Pdf::loadView('hr.report-artifact',['title'=>$title,'columns'=>$c,'rows'=>$r])->setPaper('a4','landscape')->output();return['content'=>$body,'extension'=>'pdf','mime'=>'application/pdf'];}
private function xlsx(array$c,array$r):array{abort_unless(class_exists(ZipArchive::class),500,'The PHP ZIP extension is required for XLSX generation.');$all=array_merge([$c],array_map(fn($row)=>array_map(fn($key)=>$this->scalar($row[$key]??null),$c),$r));$xml='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';foreach($all as$i=>$row){$xml.='<row r="'.($i+1).'">';foreach(array_values($row)as$j=>$value){$cell=$this->column($j).($i+1);$xml.='<c r="'.$cell.'" t="inlineStr"><is><t xml:space="preserve">'.htmlspecialchars((string)$value,ENT_XML1|ENT_QUOTES,'UTF-8').'</t></is></c>';}$xml.='</row>';}$xml.='</sheetData></worksheet>';$tmp=tempnam(sys_get_temp_dir(),'hr-report-');$zip=new ZipArchive();if($zip->open($tmp,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)throw new RuntimeException('Could not create XLSX archive.');$zip->addFromString('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');$zip->addFromString('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');$zip->addFromString('xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="HR Report" sheetId="1" r:id="rId1"/></sheets></workbook>');$zip->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');$zip->addFromString('xl/worksheets/sheet1.xml',$xml);$zip->close();$body=file_get_contents($tmp);unlink($tmp);return['content'=>$body,'extension'=>'xlsx','mime'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'];}
private function scalar(mixed$v):string{return is_array($v)||is_object($v)?json_encode($v,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR):(string)($v??'');}private function column(int$n):string{$s='';do{$s=chr(65+($n%26)).$s;$n=intdiv($n,26)-1;}while($n>=0);return$s;}}
