<?php
namespace App\Http\Controllers\Api\Hr;use App\Http\Controllers\Controller;use App\Models\Staff;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class HrGovernanceController extends Controller{
public function queues(Request$r):JsonResponse{$a=$this->actor($r);$u=$r->user();$data=[];
if($u->can('hr.engagement.approve'))$data['announcements']=DB::table('hr_announcements')->where('company_id',$a->company_id)->where('status','pending_approval')->select(['id','title','priority','publish_at','expires_at','content_checksum','created_by','created_at'])->latest()->limit(100)->get();
if($u->can('hr.surveys.approve'))$data['surveys']=DB::table('hr_survey_versions')->where('company_id',$a->company_id)->where('status','pending_approval')->select(['id','code','version','title','survey_type','anonymous','minimum_report_group','opens_at','closes_at','survey_checksum','created_by'])->latest()->limit(100)->get();
if($u->can('hr.recognition.approve'))$data['recognition']=DB::table('hr_recognition_nominations')->where('company_id',$a->company_id)->where('status','pending_approval')->select(['id','nominee_staff_id','nominator_staff_id','achievement_id','category','citation','visibility','reward_proposal','nomination_checksum','created_at'])->latest()->limit(100)->get();
if($u->can('hr.wellness.case.manage'))$data['wellness']=DB::table('hr_wellness_referrals')->where('company_id',$a->company_id)->whereIn('status',['requested','assigned','in_support'])->select(['id','staff_id','program_id','referral_type','status','case_owner_staff_id','created_at'])->latest()->limit(100)->get();
if($u->can('hr.analytics.approve'))$data['analytics_definitions']=DB::table('hr_analytics_definition_versions')->where('company_id',$a->company_id)->where('status','pending_approval')->select(['id','metric_code','version','name','minimum_group_size','effective_from','effective_until','definition_checksum','created_by'])->latest()->limit(100)->get();
if($u->can('hr.workforce-planning.approve'))$data['workforce_plans']=DB::table('hr_workforce_plan_versions')->where('company_id',$a->company_id)->where('status','pending_approval')->select(['id','code','version','name','baseline_as_of','horizon_start','horizon_end','currency','plan_checksum','submitted_by','submitted_at'])->latest()->limit(100)->get();
if($u->can('hr.reporting.approve'))$data['report_schedules']=DB::table('hr_report_schedules')->where('company_id',$a->company_id)->whereIn('status',['pending_approval','pending_review'])->select(['id','saved_view_id','name','cadence','timezone','local_time','format','delivery_channel','next_due_at','status','schedule_checksum','created_by'])->latest()->limit(100)->get();
if($u->can('hr.notifications.approve'))$data['notification_templates']=DB::table('hr_notification_template_versions')->where('company_id',$a->company_id)->where('status','pending_approval')->select(['id','code','version','event_type','channel','mandatory','effective_from','effective_until','template_checksum','created_by'])->latest()->limit(100)->get();
$counts=collect($data)->map(fn($rows)=>$rows->count());return response()->json(['status'=>'success','data'=>['counts'=>$counts,'queues'=>$data,'generated_at'=>now()->toIso8601String()]]);}
private function actor(Request$r):Staff{return Staff::query()->where('user_id',$r->user()->id)->firstOrFail();}}
