<?php
namespace App\Http\Controllers\Api\Hr;
use App\Http\Controllers\Controller;use App\Models\Staff;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class KnowledgeController extends Controller{
 public function index(Request$r):JsonResponse{$a=$this->actor($r);$now=now()->toDateString();$q=DB::table('hr_knowledge_articles')->where('company_id',$a->company_id)->where('status','published')->whereDate('effective_from','<=',$now)->where(fn($b)=>$b->whereNull('expires_at')->orWhereDate('expires_at','>=',$now));$this->audience($q,$a);$rows=$q->select(['id','slug','title','audience','version','effective_from','expires_at','acknowledgement_required','content_checksum'])->latest('effective_from')->paginate($r->integer('per_page',50));return response()->json(['status'=>'success','data'=>$rows]);}
 public function show(Request$r,string$id):JsonResponse{$a=$this->actor($r);$q=DB::table('hr_knowledge_articles')->where('id',$id)->where('company_id',$a->company_id)->where('status','published');$this->audience($q,$a);$row=$q->first();abort_unless($row,404);return response()->json(['status'=>'success','data'=>['article'=>$row,'acknowledged'=>DB::table('hr_knowledge_acknowledgements')->where('article_id',$id)->where('staff_id',$a->id)->exists()]]);}
 public function store(Request$r):JsonResponse{$this->enabled();$d=$r->validate(['company_id'=>['required','uuid'],'slug'=>['required','string','max:180'],'title'=>['required','string','max:255'],'body'=>['required','string','max:100000'],'audience'=>['required','array'],'audience.all'=>['nullable','boolean'],'audience.staff_ids'=>['nullable','array'],'audience.staff_ids.*'=>['uuid'],'audience.staff_types'=>['nullable','array'],'audience.staff_types.*'=>['string','max:60'],'audience.organization_unit_ids'=>['nullable','array'],'audience.organization_unit_ids.*'=>['uuid'],'audience.location_codes'=>['nullable','array'],'audience.location_codes.*'=>['string','max:80'],'version'=>['required','integer','min:1'],'effective_from'=>['required','date'],'expires_at'=>['nullable','date','after_or_equal:effective_from'],'acknowledgement_required'=>['required','boolean']]);$this->company($r,$d['company_id']);$audience=$d['audience'];abort_unless(($audience['all']??false)||!empty($audience['staff_ids'])||!empty($audience['staff_types'])||!empty($audience['organization_unit_ids'])||!empty($audience['location_codes']),422,'At least one article audience is required.');$id=(string)Str::uuid();$checksum=hash('sha256',json_encode(['title'=>$d['title'],'body'=>$d['body'],'audience'=>$d['audience'],'version'=>$d['version']],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));$d['audience']=json_encode($d['audience'],JSON_THROW_ON_ERROR);DB::table('hr_knowledge_articles')->insert($d+['id'=>$id,'status'=>'draft','created_by'=>$r->user()->id,'content_checksum'=>$checksum,'created_at'=>now(),'updated_at'=>now()]);$this->event($id,'drafted',null,'draft',null,$r->user()->id);return response()->json(['status'=>'success','data'=>DB::table('hr_knowledge_articles')->find($id)],201);}
 public function publish(Request$r,string$id):JsonResponse{$this->enabled();$d=$r->validate(['reason'=>['required','string','max:1000']]);return DB::transaction(function()use($r,$id,$d){$row=DB::table('hr_knowledge_articles')->where('id',$id)->lockForUpdate()->first();abort_unless($row,404);$this->company($r,$row->company_id);abort_unless($row->status==='draft',409);abort_if($row->created_by===$r->user()->id,409,'Article author cannot approve the same version.');DB::table('hr_knowledge_articles')->where('id',$id)->update(['status'=>'published','approved_by'=>$r->user()->id,'updated_at'=>now()]);$this->event($id,'published','draft','published',$d['reason'],$r->user()->id);return response()->json(['status'=>'success','data'=>DB::table('hr_knowledge_articles')->find($id)]);});}
 public function retire(Request$r,string$id):JsonResponse{$this->enabled();$d=$r->validate(['reason'=>['required','string','max:1000']]);$row=DB::table('hr_knowledge_articles')->where('id',$id)->first();abort_unless($row,404);$this->company($r,$row->company_id);abort_unless($row->status==='published',409);DB::table('hr_knowledge_articles')->where('id',$id)->update(['status'=>'retired','updated_at'=>now()]);$this->event($id,'retired','published','retired',$d['reason'],$r->user()->id);return response()->json(['status'=>'success']);}
 public function acknowledge(Request$r,string$id):JsonResponse{$this->enabled();$a=$this->actor($r);$row=DB::table('hr_knowledge_articles')->where('id',$id)->where('company_id',$a->company_id)->where('status','published')->first();abort_unless($row,404);DB::table('hr_knowledge_acknowledgements')->insertOrIgnore(['id'=>(string)Str::uuid(),'article_id'=>$id,'staff_id'=>$a->id,'acknowledged_at'=>now(),'article_checksum'=>$row->content_checksum]);return response()->json(['status'=>'success','data'=>DB::table('hr_knowledge_acknowledgements')->where('article_id',$id)->where('staff_id',$a->id)->first()]);}
 private function audience($q,Staff$a):void{$assignment=DB::table('hr_employment_assignments')->where('staff_id',$a->id)->whereNull('effective_until')->latest('effective_from')->first();$q->where(function($b)use($a,$assignment){$b->where('audience->all',true)->orWhereJsonContains('audience->staff_ids',$a->id)->orWhereJsonContains('audience->staff_types',$a->staff_type);if($assignment?->organization_unit_id)$b->orWhereJsonContains('audience->organization_unit_ids',$assignment->organization_unit_id);if($assignment?->location_code)$b->orWhereJsonContains('audience->location_codes',$assignment->location_code);});}private function event(string$id,string$type,?string$from,?string$to,?string$reason,string$actor):void{DB::table('hr_knowledge_article_events')->insert(['id'=>(string)Str::uuid(),'article_id'=>$id,'event_type'=>$type,'from_status'=>$from,'to_status'=>$to,'reason'=>$reason,'actor_user_id'=>$actor,'occurred_at'=>now()]);}private function actor(Request$r):Staff{return Staff::query()->where('user_id',$r->user()->id)->firstOrFail();}private function company(Request$r,string$id):void{abort_unless($this->actor($r)->company_id===$id,403,'Knowledge data is outside your legal entity.');}private function enabled():void{abort_unless(config('hr.features.knowledge',false),409,'HR knowledge writes are not enabled.');}
}
