<?php

namespace App\Http\Controllers\Api\Hr;

use App\Http\Controllers\Controller;
use App\Models\Staff;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class LearningController extends Controller
{
    public function courses(Request$request):JsonResponse{$staff=$this->actor($request);return response()->json(['status'=>'success','data'=>DB::table('hr_courses')->where('company_id',$staff->company_id)->orderBy('title')->paginate($request->integer('per_page',50))]);}
    public function storeCourse(Request$request):JsonResponse{$this->enabled();$d=$request->validate(['company_id'=>['required','uuid'],'code'=>['required','string','max:80'],'title'=>['required','string','max:255'],'provider_name'=>['nullable','string','max:255'],'prerequisites'=>['nullable','array'],'cost'=>['nullable','numeric','min:0'],'currency'=>['nullable','string','size:3'],'certification'=>['required','boolean'],'validity_days'=>['nullable','integer','min:1']]);$this->company($request,$d['company_id']);$id=(string)Str::uuid();if(isset($d['prerequisites']))$d['prerequisites']=json_encode($d['prerequisites'],JSON_THROW_ON_ERROR);DB::table('hr_courses')->insert($d+['id'=>$id,'status'=>'active','created_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_courses')->find($id)],201);}
    public function storeSession(Request$request):JsonResponse{$this->enabled();$d=$request->validate(['course_id'=>['required','uuid'],'starts_at'=>['required','date'],'ends_at'=>['required','date','after:starts_at'],'timezone'=>['required','timezone'],'capacity'=>['required','integer','min:1'],'delivery_mode'=>['required',Rule::in(['classroom','virtual','hybrid','self_paced'])],'location_or_link'=>['nullable','string','max:500']]);$course=DB::table('hr_courses')->where('id',$d['course_id'])->first();abort_unless($course,404);$this->company($request,$course->company_id);$id=(string)Str::uuid();DB::table('hr_course_sessions')->insert($d+['id'=>$id,'status'=>'planned','created_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_course_sessions')->find($id)],201);}
    public function enroll(Request$request):JsonResponse{$this->enabled();$actor=$this->actor($request);$d=$request->validate(['session_id'=>['required','uuid'],'staff_id'=>['required','uuid'],'nomination_source'=>['required',Rule::in(['self','manager','hr','development_plan'])]]);$session=DB::table('hr_course_sessions as s')->join('hr_courses as c','c.id','=','s.course_id')->where('s.id',$d['session_id'])->select('s.*','c.company_id')->first();$staff=Staff::query()->whereKey($d['staff_id'])->where('company_id',$actor->company_id)->first();abort_unless($session&&$staff&&$session->company_id===$actor->company_id,422,'Session and employee must be in the same legal entity.');if($d['nomination_source']==='self')abort_unless($staff->id===$actor->id,403);$active=DB::table('hr_learning_enrollments')->where('session_id',$session->id)->whereIn('status',['approved','completed'])->count();abort_if($active >= $session->capacity,409,'The session capacity is full.');$id=(string)Str::uuid();DB::table('hr_learning_enrollments')->insert($d+['id'=>$id,'status'=>'pending_approval','nominated_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_learning_enrollments')->find($id)],201);}
    public function approve(Request$request,string$id):JsonResponse{$this->enabled();return DB::transaction(function()use($request,$id){$row=DB::table('hr_learning_enrollments as e')->join('hr_course_sessions as s','s.id','=','e.session_id')->join('hr_courses as c','c.id','=','s.course_id')->where('e.id',$id)->select('e.*','s.capacity','c.company_id')->lockForUpdate()->first();abort_unless($row,404);$this->company($request,$row->company_id);abort_unless($row->status==='pending_approval',409);abort_if($row->nominated_by===$request->user()->id,409,'The nominator cannot approve the same enrollment.');$active=DB::table('hr_learning_enrollments')->where('session_id',$row->session_id)->whereIn('status',['approved','completed'])->lockForUpdate()->count();abort_if($active >= $row->capacity,409,'The session capacity is full.');DB::table('hr_learning_enrollments')->where('id',$id)->update(['status'=>'approved','approved_by'=>$request->user()->id,'approved_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_learning_enrollments')->find($id)]);});}
    public function complete(Request$request,string$id):JsonResponse{$this->enabled();$d=$request->validate(['assessment_score'=>['nullable','numeric','between:0,100'],'evidence'=>['nullable','array']]);return DB::transaction(function()use($request,$id,$d){$row=DB::table('hr_learning_enrollments as e')->join('hr_course_sessions as s','s.id','=','e.session_id')->join('hr_courses as c','c.id','=','s.course_id')->where('e.id',$id)->select('e.*','c.company_id','c.certification','c.validity_days')->lockForUpdate()->first();abort_unless($row,404);$this->company($request,$row->company_id);abort_unless($row->status==='approved',409);$expiry=$row->certification&&$row->validity_days?now()->addDays($row->validity_days)->toDateString():null;DB::table('hr_learning_enrollments')->where('id',$id)->update(['status'=>'completed','assessment_score'=>$d['assessment_score']??null,'completed_at'=>now(),'certificate_expires_at'=>$expiry,'evidence'=>isset($d['evidence'])?json_encode($d['evidence'],JSON_THROW_ON_ERROR):null,'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_learning_enrollments')->find($id)]);});}
    private function actor(Request$r):Staff{return Staff::query()->where('user_id',$r->user()->id)->firstOrFail();}private function company(Request$r,string$id):void{abort_unless($this->actor($r)->company_id===$id,403,'Learning data is outside your legal entity.');}private function enabled():void{abort_unless(config('hr.features.learning',false),409,'HR learning writes are not enabled.');}
}
