<?php
namespace App\Http\Controllers\Api\Hr;
use App\Http\Controllers\Controller;use App\Models\Staff;use App\Services\Hr\Lifecycle\LifecycleService;use App\Services\StaffAccessService;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\Rule;
class LifecycleController extends Controller{
 public function cases(Request$r,StaffAccessService$access):JsonResponse{$staff=$access->scope(Staff::query(),$r->user())->select('id');return response()->json(['status'=>'success','data'=>DB::table('hr_lifecycle_cases')->whereIn('staff_id',$staff)->latest()->paginate($r->integer('per_page',50))]);}
 /**
  * §5.15/QH5-01: storeTemplate()/approveTemplate() were POST-only with no route to list a
  * template — so openCase()'s required template_id (which must reference an *approved*
  * template per LifecycleService::openCase()) had no way to be discovered by a caller,
  * and a pending template had no way to be found to approve it. The same "create exists,
  * no read-back" gap already closed for Attendance/Leave configuration.
  */
 public function templates(Request$r):JsonResponse{$companyId=Staff::query()->where('user_id',$r->user()->id)->value('company_id');abort_unless($companyId,403,'Lifecycle data requires a Staff legal-entity context.');$q=DB::table('hr_lifecycle_templates')->where('company_id',$companyId)->when($r->case_type,fn($b,$v)=>$b->where('case_type',$v))->when($r->status,fn($b,$v)=>$b->where('status',$v))->latest('created_at');$rows=$q->paginate($r->integer('per_page',50));$rows->getCollection()->transform(fn($row)=>(array)$row+['applicability'=>json_decode($row->applicability,true,512,JSON_THROW_ON_ERROR),'task_definitions'=>json_decode($row->task_definitions,true,512,JSON_THROW_ON_ERROR)]);return response()->json(['status'=>'success','data'=>$rows]);}
 public function caseSubjectOptions(Request$r):JsonResponse{$d=$r->validate(['company_id'=>['required','uuid'],'record_type'=>['required',Rule::in(['staff','application'])],'search'=>['nullable','string','max:120'],'selected_id'=>['nullable','uuid'],'page'=>['nullable','integer','min:1'],'per_page'=>['nullable','integer','min:1','max:50']]);$this->company($r,$d['company_id']);$term=trim((string)($d['search']??''));if($d['record_type']==='staff'){$q=DB::table('staff')->leftJoin('users','users.id','=','staff.user_id')->where('staff.company_id',$d['company_id'])->whereNull('staff.deleted_at')->whereNull('staff.employment_ended_at')->when($d['selected_id']??null,fn($b,$id)=>$b->where('staff.id',$id))->when($term!==''&&empty($d['selected_id']),fn($b)=>$b->where(fn($m)=>$m->whereRaw('LOWER(staff.code) LIKE ?',['%'.mb_strtolower($term).'%'])->orWhereRaw('LOWER(users.first_name) LIKE ?',['%'.mb_strtolower($term).'%'])->orWhereRaw('LOWER(users.last_name) LIKE ?',['%'.mb_strtolower($term).'%'])))->select(['staff.id','staff.code','staff.staff_type','users.first_name','users.last_name'])->orderBy('users.first_name')->orderBy('staff.id');$map=fn($row)=>['value'=>(string)$row->id,'label'=>trim(trim(($row->first_name??'').' '.($row->last_name??'')).' · '.($row->code?:'No Staff code')),'metadata'=>['staff_type'=>$row->staff_type],'status'=>'active'];}else{$q=DB::table('hr_candidate_applications as app')->join('hr_candidates as candidate','candidate.id','=','app.candidate_id')->join('hr_job_requisitions as req','req.id','=','app.requisition_id')->where('app.company_id',$d['company_id'])->where('app.status','active')->when($d['selected_id']??null,fn($b,$id)=>$b->where('app.id',$id))->when($term!==''&&empty($d['selected_id']),fn($b)=>$b->where(fn($m)=>$m->whereRaw('LOWER(candidate.candidate_code) LIKE ?',['%'.mb_strtolower($term).'%'])->orWhereRaw('LOWER(req.code) LIKE ?',['%'.mb_strtolower($term).'%'])->orWhereRaw('LOWER(req.title) LIKE ?',['%'.mb_strtolower($term).'%'])))->select(['app.id','app.stage','candidate.candidate_code','req.code as requisition_code','req.title as requisition_title'])->orderBy('candidate.candidate_code')->orderBy('app.id');$map=fn($row)=>['value'=>(string)$row->id,'label'=>$row->candidate_code.' · '.$row->requisition_title,'metadata'=>['requisition'=>$row->requisition_code,'stage'=>$row->stage],'status'=>'active'];}$rows=$q->paginate((int)($d['per_page']??25));$rows->getCollection()->transform($map);return response()->json(['status'=>'success','data'=>$rows]);}
 public function storeTemplate(Request$r):JsonResponse{$this->enabled();$d=$r->validate(['company_id'=>['required','uuid'],'case_type'=>['required',Rule::in(['preboarding','onboarding','probation','transfer','offboarding'])],'code'=>['required','string','max:80'],'version'=>['required','integer','min:1'],'applicability'=>['required','array'],'task_definitions'=>['required','array','min:1'],'task_definitions.*.code'=>['required','string','max:80'],'task_definitions.*.title'=>['required','string','max:255']]);$this->company($r,$d['company_id']);$id=(string)Str::uuid();foreach(['applicability','task_definitions']as$k)$d[$k]=json_encode($d[$k],JSON_THROW_ON_ERROR);DB::table('hr_lifecycle_templates')->insert($d+['id'=>$id,'status'=>'pending_approval','created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_lifecycle_templates')->find($id)],201);}
 public function approveTemplate(Request$r,string$id):JsonResponse{return DB::transaction(function()use($r,$id){$row=DB::table('hr_lifecycle_templates')->where('id',$id)->lockForUpdate()->first();abort_unless($row,404);$this->company($r,$row->company_id);abort_if($row->created_by===$r->user()->id,409,'Template creator cannot approve it.');abort_unless($row->status==='pending_approval',409);DB::table('hr_lifecycle_templates')->where('id',$id)->update(['status'=>'approved','approved_by'=>$r->user()->id,'approved_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_lifecycle_templates')->find($id)]);});}
 public function openCase(Request$r,LifecycleService$s):JsonResponse{$this->enabled();$d=$r->validate(['company_id'=>['required','uuid'],'staff_id'=>['nullable','uuid','required_without:application_id','prohibited_with:application_id'],'application_id'=>['nullable','uuid','required_without:staff_id','prohibited_with:staff_id'],'template_id'=>['required','uuid'],'effective_date'=>['required','date']]);$this->company($r,$d['company_id']);return response()->json(['status'=>'success','data'=>$s->openCase($d,$r->user()->id)],201);}
 public function completeTask(Request$r,string$id,LifecycleService$s):JsonResponse{$d=$r->validate(['evidence'=>['required','array']]);return response()->json(['status'=>'success','data'=>$s->completeTask($id,$d['evidence'],$r->user()->id,$this->actorCompanyId($r))]);}
 public function startProbation(Request$r):JsonResponse{$this->enabled();$d=$r->validate(['staff_id'=>['required','uuid','exists:staff,id'],'starts_at'=>['required','date'],'review_due_at'=>['required','date','after_or_equal:starts_at'],'current_end_at'=>['required','date','after_or_equal:review_due_at'],'objectives'=>['required','array','min:1']]);$staff=Staff::query()->findOrFail($d['staff_id']);$this->company($r,$staff->company_id);$spell=DB::table('hr_employment_spells')->where('staff_id',$staff->id)->where('status','active')->first();abort_unless($spell,422,'An active employment spell is required.');abort_if(DB::table('hr_probation_cases')->where('employment_spell_id',$spell->id)->where('status','active')->exists(),409,'An active probation case already exists.');$id=(string)Str::uuid();$d['objectives']=json_encode($d['objectives'],JSON_THROW_ON_ERROR);DB::table('hr_probation_cases')->insert($d+['id'=>$id,'employment_spell_id'=>$spell->id,'status'=>'active','created_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_probation_cases')->find($id)],201);}
 public function decideProbation(Request$r,string$id):JsonResponse{$d=$r->validate(['outcome'=>['required',Rule::in(['confirmed','extended','separated'])],'new_end_at'=>['nullable','required_if:outcome,extended','date'],'reason'=>['required','string','max:2000']]);return DB::transaction(function()use($r,$id,$d){$row=DB::table('hr_probation_cases')->where('id',$id)->lockForUpdate()->first();abort_unless($row,404);$staff=Staff::query()->findOrFail($row->staff_id);$this->company($r,$staff->company_id);abort_unless($row->status==='active',409);if($d['outcome']==='extended'){abort_unless($d['new_end_at']>$row->current_end_at,422,'Probation extension must move the end date forward.');DB::table('hr_probation_cases')->where('id',$id)->update(['current_end_at'=>$d['new_end_at'],'proposed_outcome'=>'extended','decision_reason'=>$d['reason'],'decided_by'=>$r->user()->id,'decided_at'=>now(),'updated_at'=>now()]);}else{DB::table('hr_probation_cases')->where('id',$id)->update(['status'=>'completed','proposed_outcome'=>$d['outcome'],'final_outcome'=>$d['outcome'],'decision_reason'=>$d['reason'],'decided_by'=>$r->user()->id,'decided_at'=>now(),'updated_at'=>now()]);if($d['outcome']==='confirmed')DB::table('hr_employment_spells')->where('id',$row->employment_spell_id)->update(['confirmation_date'=>now()->toDateString(),'updated_at'=>now()]);}return response()->json(['status'=>'success','data'=>DB::table('hr_probation_cases')->find($id)]);});}
 public function assignCustody(Request$r):JsonResponse{$this->enabled();$d=$r->validate(['company_id'=>['required','uuid'],'staff_id'=>['required','uuid'],'custody_type'=>['required',Rule::in(['asset','access','phone_sim'])],'item_code'=>['required','string','max:120'],'item_name'=>['required','string','max:255'],'details'=>['nullable','array'],'assigned_at'=>['required','date'],'due_back_at'=>['nullable','date','after_or_equal:assigned_at'],'condition_snapshot'=>['nullable','array']]);$this->company($r,$d['company_id']);abort_if(config('hr.features.advanced_assets',false)&&in_array($d['custody_type'],['asset','phone_sim'],true),409,'Use the governed advanced asset request, approval, and issue workflow.');abort_unless(Staff::query()->whereKey($d['staff_id'])->where('company_id',$d['company_id'])->exists(),422);$id=(string)Str::uuid();DB::table('hr_custody_assignments')->insert(['id'=>$id,'company_id'=>$d['company_id'],'staff_id'=>$d['staff_id'],'custody_type'=>$d['custody_type'],'item_code'=>$d['item_code'],'item_name'=>$d['item_name'],'encrypted_details'=>isset($d['details'])?encrypt($d['details']):null,'assigned_at'=>$d['assigned_at'],'due_back_at'=>$d['due_back_at']??null,'status'=>'assigned','condition_snapshot'=>json_encode($d['condition_snapshot']??null,JSON_THROW_ON_ERROR),'assigned_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>'success','data'=>DB::table('hr_custody_assignments')->select(['id','staff_id','custody_type','item_code','item_name','assigned_at','due_back_at','status'])->find($id)],201);}
 public function requestChange(Request$r,string$staffId,LifecycleService$s,StaffAccessService$access):JsonResponse{$d=$r->validate(['change_type'=>['required',Rule::in(['transfer','promotion','manager_change','location_change','work_pattern_change'])],'effective_date'=>['required','date'],'proposed_snapshot'=>['required','array'],'impact_snapshot'=>['required','array'],'reason'=>['required','string','max:2000'],'approver_staff_id'=>['nullable','uuid'],'sla_hours'=>['nullable','integer','min:1'],'idempotency_key'=>['required','string','max:160']]);$staff=Staff::query()->findOrFail($staffId);$access->authorize($r->user(),$staff,'view');return response()->json(['status'=>'success','data'=>$s->requestChange($staff,$d,$r->user()->id)],201);}
 public function approveChange(Request$r,string$id,LifecycleService$s):JsonResponse{$row=DB::table('hr_employee_change_requests')->find($id);abort_unless($row,404);$this->company($r,$row->company_id);return response()->json(['status'=>'success','data'=>$s->approveChange($id,$r->user()->id)]);}
 public function openExit(Request$r,LifecycleService$s):JsonResponse{$this->enabled();$d=$r->validate(['company_id'=>['required','uuid'],'staff_id'=>['required','uuid'],'exit_type'=>['required',Rule::in(['resignation','termination','retirement','death_in_service'])],'notice_date'=>['nullable','date'],'proposed_last_working_date'=>['required','date'],'reason_code'=>['required','string','max:80'],'protected_reason'=>['nullable','string','max:4000'],'impact_snapshot'=>['required','array'],'rehire_eligible'=>['nullable','boolean']]);$this->company($r,$d['company_id']);abort_unless(Staff::query()->whereKey($d['staff_id'])->where('company_id',$d['company_id'])->exists(),422);$id=(string)Str::uuid();$d['impact_snapshot']=json_encode($d['impact_snapshot'],JSON_THROW_ON_ERROR);$d['protected_reason']=isset($d['protected_reason'])?encrypt($d['protected_reason']):null;DB::table('hr_exit_cases')->insert($d+['id'=>$id,'status'=>'pending_approval','opened_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);app(\App\Services\Hr\Ess\HrRequestIndexService::class)->register($d['company_id'],$d['staff_id'],'exit','exit_case',$id,'pending_approval','Employment exit request',null,48,$r->user()->id,['attendance'=>config('hr.features.attendance_results'),'leave'=>config('hr.features.leave_overtime'),'payroll'=>config('hr.features.payroll')]);return response()->json(['status'=>'success','data'=>DB::table('hr_exit_cases')->select(['id','staff_id','exit_type','proposed_last_working_date','reason_code','status'])->find($id)],201);}
 public function approveExit(Request$r,string$id,LifecycleService$s):JsonResponse{$row=DB::table('hr_exit_cases')->find($id);abort_unless($row,404);$this->company($r,$row->company_id);return response()->json(['status'=>'success','data'=>$s->approveExit($id,$r->user()->id)]);}
 public function completeClearance(Request$r,string$id,LifecycleService$s):JsonResponse{$d=$r->validate(['resolution'=>['required','string','max:2000']]);return response()->json(['status'=>'success','data'=>$s->completeClearance($id,$d['resolution'],$r->user()->id,$this->actorCompanyId($r))]);}
 public function finalizeExit(Request$r,string$id,LifecycleService$s):JsonResponse{$row=DB::table('hr_exit_cases')->find($id);abort_unless($row,404);$this->company($r,$row->company_id);return response()->json(['status'=>'success','data'=>$s->finalizeExit($id,$r->user())]);}
 private function actorCompanyId(Request$r):string{$company=Staff::query()->where('user_id',$r->user()->id)->value('company_id');abort_unless($company,403,'Lifecycle data requires a Staff legal-entity context.');return(string)$company;}private function company(Request$r,string$id):void{abort_unless($this->actorCompanyId($r)===$id,403,'Lifecycle data is outside your legal entity.');}private function enabled():void{abort_unless(config('hr.features.employee_self_service',false),409,'HR lifecycle writes are not enabled.');}
}
