<?php
namespace App\Http\Controllers\Api\Hr;
use App\Http\Controllers\Controller;use App\Models\Staff;use App\Services\StaffAccessService;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\Rule;
class TravelController extends Controller{
 public function index(Request$r):JsonResponse{$a=$this->actor($r);$q=DB::table('hr_travel_requests')->where('company_id',$a->company_id)->select(['id','staff_id','request_number','origin','destination','departs_at','returns_at','currency','estimated_cost','requested_advance','status','booking_reference','unused_advance_amount','requested_by','settlement_claim_id']);if(!$r->user()->can('hr.travel.view-all'))$q->where('staff_id',$a->id);return response()->json(['status'=>'success','data'=>$q->latest('departs_at')->paginate($r->integer('per_page',50))]);}
 public function settlementClaimOptions(Request $r, string $id): JsonResponse
 {
  $d = $r->validate([
   'search' => ['nullable', 'string', 'max:120'], 'selected_id' => ['nullable', 'uuid'],
   'page' => ['nullable', 'integer', 'min:1'], 'per_page' => ['nullable', 'integer', 'min:1', 'max:50'],
  ]);
  $travel = DB::table('hr_travel_requests')->where('id', $id)->first();
  abort_unless($travel, 404);
  $this->company($r, $travel->company_id);
  if ($travel->status !== 'approved') return response()->json(['status' => 'success', 'data' => []]);

  $q = DB::table('hr_expense_claims as claim')->where('claim.company_id', $travel->company_id)
   ->where('claim.staff_id', $travel->staff_id)->where('claim.claim_type', 'travel')->where('claim.status', 'approved')->whereNotNull('claim.approved_amount')
   ->where('claim.currency', $travel->currency)
   ->whereNotExists(fn ($linked) => $linked->selectRaw('1')->from('hr_travel_requests as request')
    ->whereColumn('request.settlement_claim_id', 'claim.id')->where('request.id', '<>', $id));
  if (!empty($d['selected_id'])) $q->where('claim.id', $d['selected_id']);
  elseif (!empty($d['search'])) $q->whereRaw('LOWER(claim.claim_number) LIKE ?', ['%'.strtolower(addcslashes(trim($d['search']), '%_\\')).'%']);
  $q->select(['claim.id', 'claim.claim_number', 'claim.currency', 'claim.approved_amount'])
   ->orderBy('claim.claim_number')->orderBy('claim.id');
  $map = fn ($claim) => [
   'value' => (string) $claim->id,
   'label' => $claim->claim_number.' · '.$claim->currency.' '.$claim->approved_amount,
   'metadata' => ['currency' => $claim->currency], 'status' => 'approved',
  ];
  if (!empty($d['selected_id'])) return response()->json(['status' => 'success', 'data' => $q->limit(1)->get()->map($map)->values()]);
  $rows = $q->paginate($d['per_page'] ?? 25);
  $rows->getCollection()->transform($map);
  return response()->json(['status' => 'success', 'data' => $rows]);
 }
 public function store(Request$r):JsonResponse{$a=$this->actor($r);$d=$r->validate(['request_number'=>['required','string','max:80'],'purpose'=>['required','string','max:4000'],'origin'=>['required','string','max:255'],'destination'=>['required','string','max:255'],'departs_at'=>['required','date'],'returns_at'=>['required','date','after:departs_at'],'timezone'=>['required','timezone'],'itinerary'=>['required','array','min:1'],'currency'=>['required','string','size:3'],'estimated_cost'=>['required','numeric','min:0'],'requested_advance'=>['required','numeric','min:0'],'per_diem_snapshot'=>['nullable','array'],'allocation_snapshot'=>['required','array']]);abort_if((float)$d['requested_advance']>(float)$d['estimated_cost'],422,'Requested advance cannot exceed estimated travel cost.');$id=(string)Str::uuid();foreach(['itinerary','per_diem_snapshot','allocation_snapshot']as$key)if(isset($d[$key]))$d[$key]=json_encode($d[$key],JSON_THROW_ON_ERROR);$d['currency']=strtoupper($d['currency']);DB::table('hr_travel_requests')->insert($d+['id'=>$id,'company_id'=>$a->company_id,'staff_id'=>$a->id,'status'=>'pending_approval','requested_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$this->event($id,'submitted',null,'pending_approval',[],$r->user()->id);app(\App\Services\Hr\Ess\HrRequestIndexService::class)->register($a->company_id,$a->id,'travel','travel_request',$id,'pending_approval','Travel request '.$d['origin'].' to '.$d['destination'],null,48,$r->user()->id,['expenses'=>true,'accounting_handoff'=>true]);return response()->json(['status'=>'success','data'=>DB::table('hr_travel_requests')->find($id)],201);}
 public function decide(Request$r,string$id):JsonResponse{$d=$r->validate(['decision'=>['required',Rule::in(['approved','rejected','returned'])],'reason'=>['required','string','max:2000'],'booking_reference'=>['nullable','string','max:160']]);return DB::transaction(function()use($r,$id,$d){$q=DB::table('hr_travel_requests')->where('id',$id)->lockForUpdate()->first();abort_unless($q,404);$this->company($r,$q->company_id);abort_unless(in_array($q->status,['pending_approval','returned'],true),409);abort_if($q->requested_by===$r->user()->id&&$d['decision']==='approved',409,'Requestor cannot approve the same travel request.');DB::table('hr_travel_requests')->where('id',$id)->update(['status'=>$d['decision'],'approved_by'=>$d['decision']==='approved'?$r->user()->id:null,'approved_at'=>$d['decision']==='approved'?now():null,'booking_reference'=>$d['booking_reference']??$q->booking_reference,'updated_at'=>now()]);$this->event($id,$d['decision'],$q->status,$d['decision'],['reason'=>$d['reason'],'booking_reference'=>$d['booking_reference']??null],$r->user()->id);app(\App\Services\Hr\Ess\HrRequestIndexService::class)->transition('travel_request',$id,$d['decision'],$d['reason'],$r->user()->id);return response()->json(['status'=>'success','data'=>DB::table('hr_travel_requests')->find($id)]);});}
 public function settle(Request$r,string$id):JsonResponse{$d=$r->validate(['expense_claim_id'=>['required','uuid'],'unused_advance_amount'=>['required','numeric','min:0'],'evidence'=>['required','array']]);return DB::transaction(function()use($r,$id,$d){$q=DB::table('hr_travel_requests')->where('id',$id)->lockForUpdate()->first();abort_unless($q,404);$this->company($r,$q->company_id);abort_unless($q->status==='approved',409);$claim=DB::table('hr_expense_claims')->where('id',$d['expense_claim_id'])->where('company_id',$q->company_id)->where('staff_id',$q->staff_id)->where('claim_type','travel')->where('status','approved')->whereNotNull('approved_amount')->where('currency',$q->currency)->lockForUpdate()->first();abort_unless($claim,422,'An approved travel claim with an approved amount and matching currency for the employee is required.');abort_if(DB::table('hr_travel_requests')->where('settlement_claim_id',$claim->id)->where('id','<>',$id)->lockForUpdate()->exists(),409,'Travel expense claim is already linked to another settlement.');abort_if((float)$d['unused_advance_amount']>(float)$q->requested_advance,422);DB::table('hr_travel_requests')->where('id',$id)->update(['status'=>'settled','settlement_claim_id'=>$claim->id,'unused_advance_amount'=>$d['unused_advance_amount'],'updated_at'=>now()]);$this->event($id,'settled',$q->status,'settled',['expense_claim_id'=>$claim->id,'unused_advance_amount'=>$d['unused_advance_amount'],'evidence'=>$d['evidence']],$r->user()->id);if((float)$d['unused_advance_amount']>0){$payload=['travel_request_id'=>$id,'staff_id'=>$q->staff_id,'unused_advance_amount'=>$d['unused_advance_amount'],'currency'=>$q->currency,'action'=>'recover_unused_travel_advance'];DB::table('hr_accounting_outbox')->insert(['id'=>(string)Str::uuid(),'company_id'=>$q->company_id,'event_type'=>'travel_advance_recovery_required','aggregate_type'=>'travel_request','aggregate_id'=>$id,'payload'=>json_encode($payload,JSON_THROW_ON_ERROR),'payload_checksum'=>hash('sha256',json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)),'status'=>'pending','available_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);}app(\App\Services\Hr\Ess\HrRequestIndexService::class)->transition('travel_request',$id,'completed','Travel settlement recorded.',$r->user()->id,null,'expense_claim',$claim->id);return response()->json(['status'=>'success','data'=>DB::table('hr_travel_requests')->find($id)]);});}
 private function event(string$id,string$type,?string$from,?string$to,array$e,string$actor):void{DB::table('hr_travel_request_events')->insert(['id'=>(string)Str::uuid(),'travel_request_id'=>$id,'event_type'=>$type,'from_status'=>$from,'to_status'=>$to,'evidence'=>json_encode($e,JSON_THROW_ON_ERROR),'actor_user_id'=>$actor,'occurred_at'=>now()]);}private function actor(Request$r):Staff{return app(StaffAccessService::class)->currentActorStaff($r->user());}private function company(Request$r,string$id):void{abort_unless($this->actor($r)->company_id===$id,403,'Travel data is outside your legal entity.');}
}
