<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::table('hr_development_plans',function(Blueprint$t){$t->foreignUuid('company_id')->nullable()->after('id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('review_id')->nullable()->after('staff_id')->constrained('hr_performance_reviews')->restrictOnDelete();$t->foreignUuid('manager_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->char('content_checksum',64)->nullable();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->text('decision_reason')->nullable();});
Schema::create('hr_development_plan_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('development_plan_id')->constrained('hr_development_plans')->restrictOnDelete();$t->string('event_type',60);$t->string('from_status',30)->nullable();$t->string('to_status',30)->nullable();$t->json('evidence')->nullable();$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('occurred_at');$t->index(['development_plan_id','occurred_at']);});
Schema::create('hr_performance_appeals',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('review_id')->constrained('hr_performance_reviews')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->text('encrypted_reason');$t->json('evidence')->nullable();$t->string('status',30)->default('submitted');$t->foreignUuid('submitted_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('resolved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('resolved_at')->nullable();$t->text('encrypted_resolution')->nullable();$t->timestamps();$t->unique('review_id');});
Schema::create('hr_continuous_feedback',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('subject_staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('author_staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('review_id')->nullable()->constrained('hr_performance_reviews')->restrictOnDelete();$t->foreignUuid('goal_id')->nullable()->constrained('hr_goals')->restrictOnDelete();$t->string('feedback_kind',30);$t->string('visibility',30);$t->text('encrypted_feedback');$t->json('evidence')->nullable();$t->timestamp('occurred_at');$t->timestamp('acknowledged_at')->nullable();$t->timestamps();$t->index(['subject_staff_id','occurred_at']);});
Schema::create('hr_critical_role_plans',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('position_id')->constrained('hr_positions')->restrictOnDelete();$t->string('criticality',30);$t->string('vacancy_risk',30);$t->json('success_profile');$t->string('status',30)->default('active');$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['company_id','position_id']);});
Schema::create('hr_succession_candidates',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('critical_role_plan_id')->constrained('hr_critical_role_plans')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('readiness',30);$t->json('gap_snapshot');$t->json('development_actions')->nullable();$t->string('status',30)->default('pending_approval');$t->foreignUuid('nominated_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->text('decision_reason')->nullable();$t->timestamps();$t->unique(['critical_role_plan_id','staff_id']);});
Schema::create('hr_talent_recommendations',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('review_id')->nullable()->constrained('hr_performance_reviews')->restrictOnDelete();$t->string('recommendation_kind',40);$t->date('proposed_effective_date');$t->json('recommendation_snapshot');$t->json('impact_snapshot');$t->text('reason');$t->string('status',30)->default('pending_approval');$t->foreignUuid('recommended_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->foreignUuid('result_change_request_id')->nullable()->constrained('hr_employee_change_requests')->restrictOnDelete();$t->timestamps();});
Schema::create('hr_talent_events',function(Blueprint$t){$t->uuid('id')->primary();$t->string('aggregate_type',60);$t->uuid('aggregate_id');$t->string('event_type',60);$t->string('from_status',30)->nullable();$t->string('to_status',30)->nullable();$t->json('evidence')->nullable();$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('occurred_at');$t->index(['aggregate_type','aggregate_id','occurred_at']);});
}public function down():void{foreach(['hr_talent_events','hr_talent_recommendations','hr_succession_candidates','hr_critical_role_plans','hr_continuous_feedback','hr_performance_appeals','hr_development_plan_events']as$table)Schema::dropIfExists($table);Schema::table('hr_development_plans',function(Blueprint$t){$t->dropConstrainedForeignId('company_id');$t->dropConstrainedForeignId('review_id');$t->dropConstrainedForeignId('manager_staff_id');$t->dropConstrainedForeignId('approved_by');$t->dropColumn(['content_checksum','approved_at','decision_reason']);});}};
