<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('hr_attendance_connectors', function(Blueprint $table){$table->uuid('id')->primary();$table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$table->string('name');$table->string('topology',40);$table->string('connector_key',100)->unique();$table->text('signing_secret');$table->string('status',30)->default('pending');$table->string('allowed_ip_cidrs',2000)->nullable();$table->timestamp('last_heartbeat_at')->nullable();$table->json('capabilities')->nullable();$table->foreignUuid('created_user_id')->constrained('users')->restrictOnDelete();$table->timestamps();});
        Schema::create('hr_attendance_devices', function(Blueprint $table){$table->uuid('id')->primary();$table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$table->foreignUuid('connector_id')->nullable()->constrained('hr_attendance_connectors')->restrictOnDelete();$table->foreignUuid('organization_unit_id')->nullable()->constrained('hr_organization_units')->restrictOnDelete();$table->string('provider',60);$table->string('integration_mode',40);$table->string('model',120)->nullable();$table->string('serial_number',160);$table->string('firmware',100)->nullable();$table->string('site_code',80);$table->string('timezone',80);$table->json('capabilities')->nullable();$table->text('encrypted_configuration')->nullable();$table->string('status',30)->default('pending');$table->timestamp('last_sync_at')->nullable();$table->timestamp('last_event_at')->nullable();$table->foreignUuid('created_user_id')->constrained('users')->restrictOnDelete();$table->timestamps();$table->unique(['provider','serial_number']);$table->index(['company_id','status']);});
        Schema::create('hr_attendance_person_mappings', function(Blueprint $table){$table->uuid('id')->primary();$table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$table->foreignUuid('device_id')->nullable()->constrained('hr_attendance_devices')->restrictOnDelete();$table->string('provider_person_id',160);$table->string('employee_number_snapshot',100);$table->string('enrollment_status',30)->default('pending');$table->json('enrolled_methods')->nullable();$table->date('effective_from');$table->date('effective_until')->nullable();$table->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$table->timestamp('last_verified_at')->nullable();$table->foreignUuid('verified_by')->nullable()->constrained('users')->restrictOnDelete();$table->timestamps();$table->index(['company_id','device_id','provider_person_id'],'hr_attendance_provider_person_index');$table->index(['staff_id','effective_from','effective_until']);});
        Schema::create('hr_attendance_ingestion_requests', function(Blueprint $table){$table->uuid('id')->primary();$table->foreignUuid('connector_id')->constrained('hr_attendance_connectors')->restrictOnDelete();$table->string('request_id',160)->unique();$table->string('nonce',160)->unique();$table->timestamp('signed_at');$table->timestamp('received_at');$table->char('payload_checksum',64);$table->unsignedInteger('event_count');$table->string('status',30);$table->text('error_summary')->nullable();$table->string('source_ip',80)->nullable();$table->timestamps();});
        Schema::create('hr_attendance_raw_events', function(Blueprint $table){$table->uuid('id')->primary();$table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$table->foreignUuid('connector_id')->constrained('hr_attendance_connectors')->restrictOnDelete();$table->foreignUuid('device_id')->nullable()->constrained('hr_attendance_devices')->restrictOnDelete();$table->foreignUuid('ingestion_request_id')->constrained('hr_attendance_ingestion_requests')->restrictOnDelete();$table->foreignUuid('staff_id')->nullable()->constrained('staff')->restrictOnDelete();$table->foreignUuid('person_mapping_id')->nullable()->constrained('hr_attendance_person_mappings')->restrictOnDelete();$table->string('provider_event_id',200);$table->string('provider_person_id',160)->nullable();$table->string('employee_number',100)->nullable();$table->timestampTz('occurred_at');$table->string('source_timezone',80);$table->smallInteger('source_utc_offset_minutes');$table->string('event_kind',50);$table->string('direction',20)->nullable();$table->string('authentication_method',40)->nullable();$table->string('verification_result',30)->nullable();$table->text('encrypted_raw_payload');$table->char('payload_checksum',64);$table->string('mapping_status',30);$table->timestamp('received_at');$table->timestamps();$table->unique(['connector_id','provider_event_id']);$table->index(['staff_id','occurred_at']);$table->index(['company_id','mapping_status','occurred_at']);});
        Schema::create('hr_attendance_quarantine_items', function(Blueprint $table){$table->uuid('id')->primary();$table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$table->foreignUuid('raw_event_id')->unique()->constrained('hr_attendance_raw_events')->restrictOnDelete();$table->string('reason_code',80);$table->text('details');$table->string('status',30)->default('open');$table->foreignUuid('resolved_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$table->foreignUuid('resolved_mapping_id')->nullable()->constrained('hr_attendance_person_mappings')->restrictOnDelete();$table->foreignUuid('resolved_by')->nullable()->constrained('users')->restrictOnDelete();$table->timestamp('resolved_at')->nullable();$table->text('resolution_reason')->nullable();$table->timestamps();$table->index(['company_id','status','reason_code']);});
        Schema::create('hr_attendance_access_commands', function(Blueprint $table){$table->uuid('id')->primary();$table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$table->foreignUuid('device_id')->nullable()->constrained('hr_attendance_devices')->restrictOnDelete();$table->string('command_type',50);$table->string('access_group_code',100)->nullable();$table->string('status',30)->default('pending_approval');$table->json('request_snapshot');$table->string('idempotency_key',160)->unique();$table->foreignUuid('requested_by')->constrained('users')->restrictOnDelete();$table->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$table->timestamp('approved_at')->nullable();$table->timestamp('delivered_at')->nullable();$table->string('provider_reference',160)->nullable();$table->text('failure_message')->nullable();$table->timestamps();});
        Schema::create('hr_attendance_sync_runs', function(Blueprint $table){$table->uuid('id')->primary();$table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$table->foreignUuid('connector_id')->nullable()->constrained('hr_attendance_connectors')->restrictOnDelete();$table->foreignUuid('device_id')->nullable()->constrained('hr_attendance_devices')->restrictOnDelete();$table->string('sync_type',50);$table->string('status',30);$table->timestamp('started_at');$table->timestamp('finished_at')->nullable();$table->unsignedInteger('read_count')->default(0);$table->unsignedInteger('created_count')->default(0);$table->unsignedInteger('duplicate_count')->default(0);$table->unsignedInteger('quarantined_count')->default(0);$table->json('cursor_snapshot')->nullable();$table->text('error_summary')->nullable();$table->timestamps();});
    }
    public function down():void{foreach(['hr_attendance_sync_runs','hr_attendance_access_commands','hr_attendance_quarantine_items','hr_attendance_raw_events','hr_attendance_ingestion_requests','hr_attendance_person_mappings','hr_attendance_devices','hr_attendance_connectors']as$table)Schema::dropIfExists($table);}
};
