<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('hr_relation_cases',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('case_number',100)->unique();$t->string('case_type',50);$t->string('severity',20);$t->string('confidentiality',30);$t->string('subject',500);$t->text('encrypted_summary');$t->string('status',30)->default('open');$t->foreignUuid('subject_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->foreignUuid('lead_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->boolean('legal_hold')->default(false);$t->date('retention_until')->nullable();$t->foreignUuid('opened_by')->constrained('users')->restrictOnDelete();$t->timestamp('closed_at')->nullable();$t->foreignUuid('closed_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamps();$t->index(['company_id','status','severity']);});
Schema::create('hr_relation_case_team',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('case_id')->constrained('hr_relation_cases')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('team_role',40);$t->json('capabilities');$t->string('status',30)->default('pending_approval');$t->date('effective_from');$t->date('effective_until')->nullable();$t->foreignUuid('nominated_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->text('decision_reason')->nullable();$t->timestamps();$t->unique(['case_id','staff_id']);});
Schema::create('hr_relation_case_participants',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('case_id')->constrained('hr_relation_cases')->restrictOnDelete();$t->foreignUuid('staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->string('participant_role',40);$t->text('encrypted_external_identity')->nullable();$t->text('encrypted_protected_notes')->nullable();$t->boolean('identity_restricted')->default(false);$t->timestamps();});
Schema::create('hr_relation_case_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('case_id')->constrained('hr_relation_cases')->restrictOnDelete();$t->string('event_type',60);$t->string('from_status',30)->nullable();$t->string('to_status',30)->nullable();$t->text('encrypted_details')->nullable();$t->json('evidence_references')->nullable();$t->char('event_checksum',64);$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('occurred_at');$t->index(['case_id','occurred_at']);});
Schema::create('hr_relation_hearings',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('case_id')->constrained('hr_relation_cases')->restrictOnDelete();$t->timestampTz('scheduled_at');$t->string('timezone',80);$t->string('location_or_link')->nullable();$t->text('encrypted_agenda');$t->text('encrypted_minutes')->nullable();$t->string('status',30)->default('scheduled');$t->foreignUuid('scheduled_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('hr_relation_appeals',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('case_id')->constrained('hr_relation_cases')->restrictOnDelete();$t->foreignUuid('appellant_staff_id')->constrained('staff')->restrictOnDelete();$t->text('encrypted_reason');$t->json('evidence_references')->nullable();$t->string('status',30)->default('submitted');$t->foreignUuid('submitted_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('resolved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('resolved_at')->nullable();$t->text('encrypted_resolution')->nullable();$t->timestamps();});
Schema::create('hr_safety_incidents',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('incident_number',100)->unique();$t->foreignUuid('reporter_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->string('incident_type',50);$t->string('severity',20);$t->string('location_code',80);$t->timestampTz('occurred_at');$t->string('source_timezone',80);$t->text('encrypted_narrative');$t->text('encrypted_immediate_action')->nullable();$t->char('report_checksum',64);$t->string('status',30)->default('reported');$t->string('regulator_status',30)->default('not_assessed');$t->string('insurance_status',30)->default('not_assessed');$t->foreignUuid('reported_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('investigator_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->timestamp('closed_at')->nullable();$t->timestamps();$t->index(['company_id','status','severity','occurred_at']);});
Schema::create('hr_safety_incident_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('incident_id')->constrained('hr_safety_incidents')->restrictOnDelete();$t->string('event_type',60);$t->string('from_status',30)->nullable();$t->string('to_status',30)->nullable();$t->json('safe_details')->nullable();$t->char('event_checksum',64);$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestampTz('occurred_at');$t->index(['incident_id','occurred_at']);});
Schema::create('hr_safety_witnesses',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('incident_id')->constrained('hr_safety_incidents')->restrictOnDelete();$t->foreignUuid('staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->text('encrypted_external_identity')->nullable();$t->text('encrypted_statement')->nullable();$t->timestamp('statement_received_at')->nullable();$t->timestamps();});
Schema::create('hr_safety_investigations',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('incident_id')->constrained('hr_safety_incidents')->restrictOnDelete();$t->unsignedInteger('version');$t->text('encrypted_findings');$t->text('encrypted_root_cause');$t->json('evidence_references')->nullable();$t->string('status',30)->default('draft');$t->foreignUuid('prepared_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['incident_id','version']);});
Schema::create('hr_safety_actions',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('incident_id')->nullable()->constrained('hr_safety_incidents')->restrictOnDelete();$t->string('action_type',40);$t->string('title',500);$t->text('description');$t->foreignUuid('owner_staff_id')->constrained('staff')->restrictOnDelete();$t->date('due_at');$t->string('status',30)->default('open');$t->json('completion_evidence')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignUuid('verified_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('verified_at')->nullable();$t->timestamps();});
Schema::create('hr_hazards',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('hazard_number',100)->unique();$t->string('location_code',80);$t->string('category',60);$t->string('title',500);$t->text('description');$t->string('likelihood',20);$t->string('impact',20);$t->string('risk_rating',20);$t->json('controls');$t->char('hazard_checksum',64);$t->string('status',30)->default('open');$t->foreignUuid('owner_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('hr_ppe_issuances',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('custody_assignment_id')->nullable()->constrained('hr_custody_assignments')->restrictOnDelete();$t->string('ppe_type',80);$t->date('issued_at');$t->date('expires_at')->nullable();$t->date('training_due_at')->nullable();$t->string('status',30)->default('issued');$t->json('evidence')->nullable();$t->char('issuance_checksum',64);$t->foreignUuid('issued_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('hr_fitness_restrictions',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('fitness_status',30);$t->json('work_restrictions');$t->text('encrypted_private_notes')->nullable();$t->date('effective_from');$t->date('effective_until')->nullable();$t->string('verification_reference',160);$t->char('restriction_checksum',64);$t->foreignUuid('recorded_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->index(['staff_id','effective_from','effective_until']);});
}public function down():void{foreach(['hr_fitness_restrictions','hr_ppe_issuances','hr_hazards','hr_safety_actions','hr_safety_investigations','hr_safety_witnesses','hr_safety_incident_events','hr_safety_incidents','hr_relation_appeals','hr_relation_hearings','hr_relation_case_events','hr_relation_case_participants','hr_relation_case_team','hr_relation_cases']as$table)Schema::dropIfExists($table);}};
