<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('hr_organization_units', function (Blueprint $table) {
            $table->uuid('id')->primary(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();
            $table->foreignUuid('parent_id')->nullable()->constrained('hr_organization_units')->restrictOnDelete();
            $table->string('unit_type', 40); $table->string('code', 80); $table->string('name', 255);
            $table->foreignUuid('manager_staff_id')->nullable()->constrained('staff')->restrictOnDelete();
            $table->foreignUuid('hr_partner_staff_id')->nullable()->constrained('staff')->restrictOnDelete();
            $table->string('timezone', 80)->default('Asia/Colombo'); $table->string('status', 30)->default('active');
            $table->date('effective_from'); $table->date('effective_until')->nullable(); $table->json('custom_fields')->nullable();
            $table->foreignUuid('created_user_id')->constrained('users')->restrictOnDelete(); $table->foreignUuid('updated_user_id')->nullable()->constrained('users')->restrictOnDelete(); $table->timestamps();
            $table->unique(['company_id', 'code']); $table->index(['company_id', 'unit_type', 'status']);
        });

        Schema::create('hr_job_families', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->string('code',80); $table->string('name'); $table->text('description')->nullable(); $table->string('status',30)->default('active'); $table->timestamps(); $table->unique(['company_id','code']); });
        Schema::create('hr_job_grades', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->string('code',80); $table->string('name'); $table->unsignedInteger('rank'); $table->decimal('minimum_salary_lkr',20,4)->nullable(); $table->decimal('maximum_salary_lkr',20,4)->nullable(); $table->string('status',30)->default('active'); $table->timestamps(); $table->unique(['company_id','code']); });
        Schema::create('hr_designations', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->foreignUuid('job_family_id')->nullable()->constrained('hr_job_families')->restrictOnDelete(); $table->foreignUuid('job_grade_id')->nullable()->constrained('hr_job_grades')->restrictOnDelete(); $table->string('code',80); $table->string('name'); $table->text('description')->nullable(); $table->string('status',30)->default('active'); $table->timestamps(); $table->unique(['company_id','code']); });
        Schema::create('hr_positions', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->foreignUuid('organization_unit_id')->constrained('hr_organization_units')->restrictOnDelete(); $table->foreignUuid('designation_id')->constrained('hr_designations')->restrictOnDelete(); $table->string('position_number',100)->unique(); $table->string('title'); $table->unsignedInteger('headcount_limit')->default(1); $table->string('status',30)->default('vacant'); $table->date('effective_from'); $table->date('effective_until')->nullable(); $table->json('custom_fields')->nullable(); $table->timestamps(); });

        Schema::create('hr_employee_number_sequences', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('company_id')->unique()->constrained('companies')->restrictOnDelete(); $table->string('template',100)->default('EMP-{NNNN}'); $table->string('prefix',30)->nullable(); $table->string('suffix',30)->nullable(); $table->unsignedBigInteger('start_value')->default(1001); $table->unsignedBigInteger('next_value')->default(1001); $table->unsignedTinyInteger('padding')->default(4); $table->string('status',30)->default('active'); $table->unsignedInteger('version')->default(1); $table->foreignUuid('updated_user_id')->nullable()->constrained('users')->restrictOnDelete(); $table->timestamps(); });
        Schema::create('hr_employee_number_aliases', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->string('employee_number',100)->unique(); $table->string('alias_type',30); $table->boolean('is_canonical')->default(false); $table->date('effective_from'); $table->date('effective_until')->nullable(); $table->text('reason')->nullable(); $table->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete(); $table->timestamps(); $table->index(['staff_id','is_canonical']); });

        Schema::create('hr_employment_types', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->string('code',80); $table->string('name'); $table->boolean('is_employee')->default(true); $table->json('rules')->nullable(); $table->string('status',30)->default('active'); $table->timestamps(); $table->unique(['company_id','code']); });
        Schema::create('hr_employment_spells', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->foreignUuid('employment_type_id')->nullable()->constrained('hr_employment_types')->restrictOnDelete(); $table->unsignedInteger('spell_number'); $table->date('joined_at'); $table->date('service_date'); $table->date('confirmation_date')->nullable(); $table->date('rehire_date')->nullable(); $table->date('last_working_date')->nullable(); $table->date('terminated_at')->nullable(); $table->string('termination_reason_code',80)->nullable(); $table->text('termination_reason')->nullable(); $table->string('status',30)->default('active'); $table->boolean('gratuity_qualified')->nullable(); $table->date('gratuity_service_start'); $table->text('gratuity_service_decision')->nullable(); $table->json('prior_service_decisions')->nullable(); $table->foreignUuid('created_user_id')->constrained('users')->restrictOnDelete(); $table->timestamps(); $table->unique(['staff_id','spell_number']); $table->index(['staff_id','status']); });
        Schema::create('hr_employment_assignments', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('employment_spell_id')->constrained('hr_employment_spells')->restrictOnDelete(); $table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->foreignUuid('position_id')->nullable()->constrained('hr_positions')->restrictOnDelete(); $table->foreignUuid('organization_unit_id')->nullable()->constrained('hr_organization_units')->restrictOnDelete(); $table->foreignUuid('manager_staff_id')->nullable()->constrained('staff')->restrictOnDelete(); $table->foreignUuid('dotted_line_manager_staff_id')->nullable()->constrained('staff')->restrictOnDelete(); $table->foreignUuid('hr_partner_staff_id')->nullable()->constrained('staff')->restrictOnDelete(); $table->string('cost_centre_code',80)->nullable(); $table->string('location_code',80)->nullable(); $table->string('payroll_group_code',80)->nullable(); $table->string('default_shift_code',80)->nullable(); $table->string('work_pattern_code',80)->nullable(); $table->string('assignment_type',40)->default('primary'); $table->date('effective_from'); $table->date('effective_until')->nullable(); $table->string('change_reason',80); $table->json('snapshot'); $table->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete(); $table->timestamps(); $table->index(['staff_id','effective_from','effective_until']); });
        Schema::create('hr_reporting_lines', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->foreignUuid('manager_staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignUuid('member_staff_id')->constrained('staff')->restrictOnDelete(); $table->string('line_type',30)->default('primary'); $table->date('effective_from'); $table->date('effective_until')->nullable(); $table->foreignUuid('created_user_id')->constrained('users')->restrictOnDelete(); $table->timestamps(); $table->index(['manager_staff_id','effective_from','effective_until']); });

        Schema::create('hr_staff_profile_versions', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete(); $table->unsignedInteger('version'); $table->text('encrypted_profile'); $table->char('profile_checksum',64); $table->string('change_reason',500); $table->foreignUuid('changed_by')->constrained('users')->restrictOnDelete(); $table->timestamp('effective_at'); $table->timestamps(); $table->unique(['staff_id','version']); });
        Schema::create('hr_employee_records', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignUuid('employment_spell_id')->nullable()->constrained('hr_employment_spells')->restrictOnDelete(); $table->string('record_type',50); $table->string('title'); $table->text('encrypted_data'); $table->date('effective_date')->nullable(); $table->date('expiry_date')->nullable(); $table->string('verification_status',30)->default('unverified'); $table->foreignUuid('verified_by')->nullable()->constrained('users')->restrictOnDelete(); $table->string('confidentiality',30)->default('hr_private'); $table->string('source',60); $table->boolean('employee_submitted')->default(false); $table->foreignUuid('supersedes_id')->nullable()->constrained('hr_employee_records')->restrictOnDelete(); $table->foreignUuid('evidence_file_id')->nullable()->constrained('domain_evidence_files')->restrictOnDelete(); $table->timestamps(); $table->index(['staff_id','record_type']); });
        Schema::create('hr_employee_timeline_events', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignUuid('employment_spell_id')->nullable()->constrained('hr_employment_spells')->restrictOnDelete(); $table->string('domain',50); $table->string('event_type',80); $table->string('source_type',80); $table->uuid('source_id'); $table->string('title'); $table->json('safe_summary'); $table->string('confidentiality',30); $table->timestamp('effective_at'); $table->timestamp('recorded_at'); $table->string('idempotency_key',160)->unique(); $table->timestamps(); $table->index(['staff_id','effective_at']); });

        Schema::create('hr_rehire_cases', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->foreignUuid('prior_spell_id')->constrained('hr_employment_spells')->restrictOnDelete(); $table->string('status',30)->default('draft'); $table->date('proposed_rehire_date'); $table->json('duplicate_match_snapshot'); $table->json('eligibility_snapshot'); $table->json('prior_service_decisions'); $table->json('access_reactivation_plan')->nullable(); $table->json('benefit_statutory_review')->nullable(); $table->foreignUuid('prepared_by')->constrained('users')->restrictOnDelete(); $table->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete(); $table->timestamp('approved_at')->nullable(); $table->foreignUuid('new_spell_id')->nullable()->constrained('hr_employment_spells')->restrictOnDelete(); $table->string('idempotency_key',160)->unique(); $table->char('request_payload_checksum',64); $table->timestamps(); });

        Schema::create('hr_custom_field_definitions', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('company_id')->constrained('companies')->restrictOnDelete(); $table->string('applies_to',40); $table->string('field_key',80); $table->string('label'); $table->string('data_type',30); $table->json('validation_rules')->nullable(); $table->string('confidentiality',30)->default('internal'); $table->boolean('required')->default(false); $table->boolean('active')->default(true); $table->timestamps(); $table->unique(['company_id','applies_to','field_key']); });
        Schema::create('hr_custom_field_values', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignUuid('definition_id')->constrained('hr_custom_field_definitions')->restrictOnDelete(); $table->string('owner_type',80); $table->uuid('owner_id'); $table->text('encrypted_value')->nullable(); $table->foreignUuid('updated_by')->constrained('users')->restrictOnDelete(); $table->timestamps(); $table->unique(['definition_id','owner_type','owner_id'],'hr_custom_field_owner_unique'); });
    }

    public function down(): void
    {
        foreach (['hr_custom_field_values','hr_custom_field_definitions','hr_rehire_cases','hr_employee_timeline_events','hr_employee_records','hr_staff_profile_versions','hr_reporting_lines','hr_employment_assignments','hr_employment_spells','hr_employment_types','hr_employee_number_aliases','hr_employee_number_sequences','hr_positions','hr_designations','hr_job_grades','hr_job_families','hr_organization_units'] as $table) Schema::dropIfExists($table);
    }
};
