<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up():void
    {
        Schema::create('hr_request_index',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('requester_staff_id')->constrained('staff')->restrictOnDelete();$t->string('request_type',60);$t->string('source_type',100);$t->uuid('source_id');$t->string('status',30);$t->string('summary',500);$t->foreignUuid('current_owner_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->timestamp('due_at')->nullable();$t->string('result_type',100)->nullable();$t->uuid('result_id')->nullable();$t->json('capability_snapshot');$t->timestamp('submitted_at');$t->timestamp('closed_at')->nullable();$t->timestamps();$t->unique(['source_type','source_id']);$t->index(['requester_staff_id','status','submitted_at']);});
        Schema::create('hr_request_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('request_index_id')->constrained('hr_request_index')->restrictOnDelete();$t->string('event_type',40);$t->string('from_status',30)->nullable();$t->string('to_status',30);$t->string('visible_to_employee_message',1000)->nullable();$t->json('private_snapshot')->nullable();$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('occurred_at');$t->timestamps();});
        Schema::create('hr_approval_delegations',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('delegator_staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('delegate_staff_id')->constrained('staff')->restrictOnDelete();$t->json('request_types');$t->date('effective_from');$t->date('effective_until');$t->string('reason',1000);$t->string('status',30)->default('pending_approval');$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->index(['delegator_staff_id','effective_from','effective_until']);});
        Schema::create('hr_job_requisitions',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('position_id')->constrained('hr_positions')->restrictOnDelete();$t->foreignUuid('organization_unit_id')->nullable()->constrained('hr_organization_units')->restrictOnDelete();$t->string('code',80)->unique();$t->string('title');$t->unsignedSmallInteger('headcount');$t->string('employment_type_code',80)->nullable();$t->json('requirements');$t->json('budget_snapshot')->nullable();$t->string('status',30)->default('pending_approval');$t->date('target_date')->nullable();$t->foreignUuid('requested_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();});
        Schema::create('hr_candidates',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('candidate_code',80)->unique();$t->text('encrypted_profile');$t->char('identity_fingerprint',64);$t->string('source_type',60);$t->string('source_reference',160)->nullable();$t->timestamp('consent_at');$t->timestamp('consent_expires_at')->nullable();$t->timestamp('erasure_requested_at')->nullable();$t->string('status',30)->default('active');$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->index(['company_id','identity_fingerprint']);});
        Schema::create('hr_candidate_applications',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('candidate_id')->constrained('hr_candidates')->restrictOnDelete();$t->foreignUuid('requisition_id')->constrained('hr_job_requisitions')->restrictOnDelete();$t->string('stage',40)->default('applied');$t->string('status',30)->default('active');$t->string('disposition_code',80)->nullable();$t->foreignUuid('owner_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->foreignUuid('converted_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->timestamp('converted_at')->nullable();$t->timestamps();$t->unique(['candidate_id','requisition_id']);});
        Schema::create('hr_candidate_application_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('application_id')->constrained('hr_candidate_applications')->restrictOnDelete();$t->string('event_type',40);$t->string('from_stage',40)->nullable();$t->string('to_stage',40);$t->text('reason');$t->json('snapshot');$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('occurred_at');$t->timestamps();});
        Schema::create('hr_candidate_interviews',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('application_id')->constrained('hr_candidate_applications')->restrictOnDelete();$t->string('interview_type',60);$t->timestampTz('scheduled_at');$t->string('timezone',80);$t->json('panel_staff_ids');$t->string('status',30)->default('scheduled');$t->text('encrypted_schedule_details')->nullable();$t->timestamps();});
        Schema::create('hr_candidate_feedback',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('interview_id')->constrained('hr_candidate_interviews')->restrictOnDelete();$t->foreignUuid('reviewer_staff_id')->constrained('staff')->restrictOnDelete();$t->text('encrypted_scorecard');$t->string('recommendation',30);$t->timestamp('submitted_at');$t->timestamps();$t->unique(['interview_id','reviewer_staff_id']);});
        Schema::create('hr_candidate_offers',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('application_id')->constrained('hr_candidate_applications')->restrictOnDelete();$t->unsignedInteger('version');$t->text('encrypted_package');$t->date('proposed_join_date');$t->date('expires_at');$t->string('status',30)->default('pending_approval');$t->foreignUuid('prepared_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamp('responded_at')->nullable();$t->text('response_reason')->nullable();$t->timestamps();$t->unique(['application_id','version']);});
        Schema::create('hr_lifecycle_templates',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('case_type',40);$t->string('code',80);$t->unsignedInteger('version');$t->json('applicability');$t->json('task_definitions');$t->string('status',30)->default('pending_approval');$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['company_id','code','version']);});
        Schema::create('hr_lifecycle_cases',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->foreignUuid('application_id')->nullable()->constrained('hr_candidate_applications')->restrictOnDelete();$t->foreignUuid('template_id')->nullable()->constrained('hr_lifecycle_templates')->restrictOnDelete();$t->string('case_type',40);$t->string('status',30)->default('open');$t->date('effective_date');$t->json('case_snapshot');$t->foreignUuid('opened_by')->constrained('users')->restrictOnDelete();$t->timestamp('closed_at')->nullable();$t->foreignUuid('closed_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamps();$t->index(['staff_id','case_type','status']);});
        Schema::create('hr_lifecycle_tasks',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('case_id')->constrained('hr_lifecycle_cases')->restrictOnDelete();$t->string('task_code',80);$t->string('title');$t->string('owner_kind',40);$t->foreignUuid('owner_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->date('due_date')->nullable();$t->json('dependency_codes')->nullable();$t->string('status',30)->default('pending');$t->json('evidence')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignUuid('completed_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['case_id','task_code']);});
        Schema::create('hr_probation_cases',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('employment_spell_id')->constrained('hr_employment_spells')->restrictOnDelete();$t->date('starts_at');$t->date('review_due_at');$t->date('current_end_at');$t->string('status',30)->default('active');$t->json('objectives');$t->json('checkins')->nullable();$t->string('proposed_outcome',30)->nullable();$t->string('final_outcome',30)->nullable();$t->text('decision_reason')->nullable();$t->foreignUuid('decided_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('decided_at')->nullable();$t->timestamps();});
        Schema::create('hr_employee_change_requests',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('change_type',40);$t->date('effective_date');$t->json('before_snapshot');$t->json('proposed_snapshot');$t->json('impact_snapshot');$t->string('status',30)->default('pending_approval');$t->text('reason');$t->string('idempotency_key',160)->unique();$t->foreignUuid('requested_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->foreignUuid('result_assignment_id')->nullable()->constrained('hr_employment_assignments')->restrictOnDelete();$t->timestamps();});
        Schema::create('hr_exit_cases',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('exit_type',40);$t->date('notice_date')->nullable();$t->date('proposed_last_working_date');$t->date('approved_last_working_date')->nullable();$t->string('reason_code',80);$t->text('protected_reason')->nullable();$t->string('status',30)->default('pending_approval');$t->json('impact_snapshot');$t->boolean('rehire_eligible')->nullable();$t->foreignUuid('opened_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();});
        Schema::create('hr_custody_assignments',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('custody_type',30);$t->string('item_code',120);$t->string('item_name');$t->text('encrypted_details')->nullable();$t->date('assigned_at');$t->date('due_back_at')->nullable();$t->timestamp('returned_at')->nullable();$t->string('status',30)->default('assigned');$t->json('condition_snapshot')->nullable();$t->foreignUuid('assigned_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('received_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['company_id','custody_type','item_code']);});
        Schema::create('hr_exit_clearance_items',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('exit_case_id')->constrained('hr_exit_cases')->restrictOnDelete();$t->string('clearance_type',40);$t->foreignUuid('custody_assignment_id')->nullable()->constrained('hr_custody_assignments')->restrictOnDelete();$t->string('title');$t->foreignUuid('owner_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->string('status',30)->default('pending');$t->text('resolution')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignUuid('completed_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamps();});
    }
    public function down():void{foreach(['hr_exit_clearance_items','hr_custody_assignments','hr_exit_cases','hr_employee_change_requests','hr_probation_cases','hr_lifecycle_tasks','hr_lifecycle_cases','hr_lifecycle_templates','hr_candidate_offers','hr_candidate_feedback','hr_candidate_interviews','hr_candidate_application_events','hr_candidate_applications','hr_candidates','hr_job_requisitions','hr_approval_delegations','hr_request_events','hr_request_index']as$table)Schema::dropIfExists($table);}
};
