<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('hr_review_cycles',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('code',80);$t->string('name');$t->date('period_start');$t->date('period_end');$t->json('stages');$t->string('status',30)->default('draft');$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['company_id','code']);});
Schema::create('hr_review_templates',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('code',80);$t->unsignedInteger('version');$t->json('applicability');$t->json('sections');$t->json('rating_scale');$t->string('status',30)->default('pending_approval');$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['company_id','code','version']);});
Schema::create('hr_performance_reviews',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('cycle_id')->constrained('hr_review_cycles')->restrictOnDelete();$t->foreignUuid('template_id')->constrained('hr_review_templates')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('manager_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->string('status',30)->default('self_review');$t->json('assignment_snapshot');$t->decimal('final_rating',8,4)->nullable();$t->text('calibration_reason')->nullable();$t->timestamp('acknowledged_at')->nullable();$t->timestamps();$t->unique(['cycle_id','staff_id']);});
Schema::create('hr_review_sales_kpi_links',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('review_id')->unique()->constrained('hr_performance_reviews')->restrictOnDelete();$t->foreignUuid('sales_kpi_snapshot_id')->constrained('sales_kpi_snapshots')->restrictOnDelete();$t->foreignUuid('sales_kpi_snapshot_row_id')->constrained('sales_kpi_snapshot_rows')->restrictOnDelete();$t->char('snapshot_checksum',64);$t->timestamp('linked_at');$t->foreignUuid('linked_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('hr_review_responses',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('review_id')->constrained('hr_performance_reviews')->restrictOnDelete();$t->string('respondent_role',30);$t->foreignUuid('respondent_staff_id')->constrained('staff')->restrictOnDelete();$t->json('responses');$t->decimal('rating',8,4)->nullable();$t->string('status',30)->default('draft');$t->timestamp('submitted_at')->nullable();$t->timestamps();$t->unique(['review_id','respondent_role','respondent_staff_id']);});
Schema::create('hr_goals',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('review_id')->nullable()->constrained('hr_performance_reviews')->restrictOnDelete();$t->uuid('parent_goal_id')->nullable()->index();$t->string('title');$t->text('description');$t->decimal('weight',8,4);$t->string('measurement_kind',30);$t->decimal('target_value',20,4)->nullable();$t->decimal('actual_value',20,4)->nullable();$t->date('starts_at');$t->date('due_at');$t->string('status',30)->default('draft');$t->json('evidence')->nullable();$t->timestamps();});
Schema::create('hr_achievements',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('category',60);$t->string('title');$t->text('description');$t->date('achievement_date');$t->json('outcome_snapshot');$t->json('evidence')->nullable();$t->string('visibility',30);$t->string('status',30)->default('pending_verification');$t->foreignUuid('submitted_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('verified_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('verified_at')->nullable();$t->text('verification_reason')->nullable();$t->timestamps();});
Schema::create('hr_development_plans',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('plan_type',30);$t->date('starts_at');$t->date('ends_at')->nullable();$t->json('objectives');$t->json('support_actions');$t->string('status',30)->default('draft');$t->text('confidential_notes')->nullable();$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('hr_talent_profiles',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('staff_id')->unique()->constrained('staff')->restrictOnDelete();$t->string('performance_band',30)->nullable();$t->string('potential_band',30)->nullable();$t->string('readiness',30)->nullable();$t->json('mobility_preferences')->nullable();$t->text('encrypted_retention_notes')->nullable();$t->foreignUuid('assessed_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('assessed_at')->nullable();$t->timestamps();});
Schema::create('hr_courses',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('code',80);$t->string('title');$t->string('provider_name')->nullable();$t->json('prerequisites')->nullable();$t->decimal('cost',20,4)->nullable();$t->string('currency',3)->nullable();$t->boolean('certification')->default(false);$t->unsignedInteger('validity_days')->nullable();$t->string('status',30)->default('active');$t->timestamps();$t->unique(['company_id','code']);});
Schema::create('hr_course_sessions',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('course_id')->constrained('hr_courses')->restrictOnDelete();$t->timestampTz('starts_at');$t->timestampTz('ends_at');$t->string('timezone',80);$t->unsignedInteger('capacity');$t->string('delivery_mode',30);$t->string('location_or_link')->nullable();$t->string('status',30)->default('planned');$t->timestamps();});
Schema::create('hr_learning_enrollments',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('session_id')->constrained('hr_course_sessions')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('nomination_source',30);$t->string('status',30)->default('pending_approval');$t->foreignUuid('nominated_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->decimal('assessment_score',8,4)->nullable();$t->timestamp('completed_at')->nullable();$t->date('certificate_expires_at')->nullable();$t->json('evidence')->nullable();$t->timestamps();$t->unique(['session_id','staff_id']);});
Schema::create('hr_expense_claims',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('claim_number',80)->unique();$t->string('claim_type',30);$t->string('currency',3);$t->decimal('claimed_amount',20,4);$t->decimal('approved_amount',20,4)->nullable();$t->string('status',30)->default('draft');$t->json('allocation_snapshot');$t->char('content_checksum',64);$t->foreignUuid('submitted_by')->nullable()->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();});
Schema::create('hr_expense_lines',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('claim_id')->constrained('hr_expense_claims')->cascadeOnDelete();$t->string('category_code',80);$t->date('expense_date');$t->string('description',500);$t->decimal('amount',20,4);$t->decimal('fx_rate',20,10)->nullable();$t->decimal('base_amount',20,4);$t->string('merchant_fingerprint',160)->nullable();$t->string('receipt_checksum',64)->nullable();$t->json('tax_snapshot')->nullable();$t->timestamps();});
Schema::create('hr_service_requests',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('request_number',80)->unique();$t->string('catalog_code',80);$t->string('priority',20);$t->string('confidentiality',30);$t->string('status',30)->default('open');$t->string('subject',500);$t->text('encrypted_details');$t->foreignUuid('assigned_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->timestamp('due_at')->nullable();$t->timestamp('resolved_at')->nullable();$t->timestamps();});
Schema::create('hr_knowledge_articles',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('slug');$t->string('title');$t->text('body');$t->json('audience');$t->unsignedInteger('version');$t->date('effective_from');$t->date('expires_at')->nullable();$t->string('status',30)->default('draft');$t->boolean('acknowledgement_required')->default(false);$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['company_id','slug','version']);});
}public function down():void{foreach(['hr_knowledge_articles','hr_service_requests','hr_expense_lines','hr_expense_claims','hr_learning_enrollments','hr_course_sessions','hr_courses','hr_talent_profiles','hr_development_plans','hr_achievements','hr_goals','hr_review_responses','hr_review_sales_kpi_links','hr_performance_reviews','hr_review_templates','hr_review_cycles']as$table)Schema::dropIfExists($table);}};
