<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('hr_report_saved_views',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('owner_user_id')->constrained('users')->restrictOnDelete();$t->string('name');$t->string('report_kind',60);$t->json('filter_contract');$t->json('column_contract');$t->string('visibility',20)->default('private');$t->string('status',20)->default('active');$t->char('view_checksum',64);$t->timestamps();$t->index(['company_id','report_kind','status']);});
Schema::create('hr_report_schedules',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('saved_view_id')->constrained('hr_report_saved_views')->restrictOnDelete();$t->string('name');$t->string('cadence',20);$t->string('timezone',80);$t->time('local_time');$t->unsignedTinyInteger('day_of_week')->nullable();$t->unsignedTinyInteger('day_of_month')->nullable();$t->string('format',10);$t->json('recipient_user_ids');$t->string('delivery_channel',20)->default('in_app');$t->timestampTz('next_due_at');$t->timestampTz('last_queued_at')->nullable();$t->string('status',30)->default('pending_approval');$t->char('schedule_checksum',64);$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->text('decision_reason')->nullable();$t->timestamps();$t->index(['status','next_due_at']);});
Schema::create('hr_report_runs',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->foreignUuid('saved_view_id')->constrained('hr_report_saved_views')->restrictOnDelete();$t->foreignUuid('schedule_id')->nullable()->constrained('hr_report_schedules')->restrictOnDelete();$t->foreignUuid('transfer_job_id')->nullable()->constrained('domain_transfer_jobs')->restrictOnDelete();$t->string('run_kind',20);$t->date('as_of_date');$t->timestampTz('cutoff_at');$t->json('filter_snapshot');$t->json('column_snapshot');$t->json('privacy_snapshot');$t->char('request_checksum',64);$t->string('idempotency_key',160)->unique();$t->string('status',30)->default('queued');$t->string('artifact_disk',40)->nullable();$t->string('artifact_path',1000)->nullable();$t->string('artifact_file_name')->nullable();$t->string('artifact_mime',160)->nullable();$t->unsignedBigInteger('artifact_size')->nullable();$t->char('artifact_checksum',64)->nullable();$t->timestampTz('artifact_expires_at')->nullable();$t->timestamp('completed_at')->nullable();$t->text('failure_message')->nullable();$t->foreignUuid('requested_by')->constrained('users')->restrictOnDelete();$t->timestamp('queued_at');$t->timestamps();$t->index(['company_id','status','queued_at']);$t->index(['artifact_expires_at','status']);});
Schema::create('hr_report_delivery_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('report_run_id')->constrained('hr_report_runs')->restrictOnDelete();$t->foreignUuid('recipient_user_id')->nullable()->constrained('users')->restrictOnDelete();$t->string('channel',20);$t->string('event_type',30);$t->string('idempotency_key',200)->nullable()->unique();$t->string('external_reference',160)->nullable();$t->text('message')->nullable();$t->char('artifact_checksum',64)->nullable();$t->foreignUuid('actor_user_id')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('occurred_at');$t->index(['report_run_id','event_type']);});
Schema::create('hr_data_quality_snapshots',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->date('as_of_date');$t->timestampTz('cutoff_at');$t->json('summary_payload');$t->char('source_checksum',64);$t->char('snapshot_checksum',64);$t->foreignUuid('generated_by')->constrained('users')->restrictOnDelete();$t->timestamp('generated_at');$t->timestamps();$t->unique(['company_id','as_of_date','source_checksum']);});
}public function down():void{foreach(['hr_data_quality_snapshots','hr_report_delivery_events','hr_report_runs','hr_report_schedules','hr_report_saved_views']as$table)Schema::dropIfExists($table);}};
