<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('hr_relation_conflicts',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('case_id')->constrained('hr_relation_cases')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->string('conflict_type',50);$t->text('encrypted_reason');$t->string('status',30)->default('declared');$t->foreignUuid('declared_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('decided_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('decided_at')->nullable();$t->text('decision_reason')->nullable();$t->timestamps();$t->unique(['case_id','staff_id']);});
Schema::create('hr_relation_case_outcomes',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('case_id')->constrained('hr_relation_cases')->restrictOnDelete();$t->unsignedInteger('version');$t->string('outcome_code',80);$t->text('encrypted_findings');$t->json('actions');$t->string('status',30)->default('pending_approval');$t->foreignUuid('prepared_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['case_id','version']);});
Schema::table('hr_relation_hearings',function(Blueprint$t){$t->foreignUuid('chair_staff_id')->nullable()->constrained('staff')->restrictOnDelete();$t->json('attendee_snapshot')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignUuid('completed_by')->nullable()->constrained('users')->restrictOnDelete();});
Schema::create('hr_safety_inspections',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('inspection_number',100)->unique();$t->string('location_code',80);$t->string('inspection_type',60);$t->date('scheduled_for');$t->string('status',30)->default('planned');$t->json('checklist_snapshot');$t->char('checklist_checksum',64);$t->json('result_snapshot')->nullable();$t->char('result_checksum',64)->nullable();$t->foreignUuid('lead_staff_id')->constrained('staff')->restrictOnDelete();$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('verified_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('verified_at')->nullable();$t->timestamps();});
Schema::table('hr_safety_actions',fn(Blueprint$t)=>$t->foreignUuid('inspection_id')->nullable()->after('incident_id')->constrained('hr_safety_inspections')->restrictOnDelete());
Schema::create('hr_safety_external_notifications',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('incident_id')->constrained('hr_safety_incidents')->restrictOnDelete();$t->string('recipient_type',30);$t->string('notification_type',60);$t->json('payload_snapshot');$t->char('payload_checksum',64);$t->string('status',30)->default('pending_approval');$t->unsignedInteger('attempt_count')->default(0);$t->timestampTz('available_at')->nullable();$t->char('lease_token',64)->nullable();$t->timestampTz('leased_until')->nullable();$t->foreignUuid('prepared_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->string('external_reference',200)->nullable();$t->timestamp('acknowledged_at')->nullable();$t->text('last_error')->nullable();$t->timestamps();$t->unique(['incident_id','recipient_type','notification_type']);$t->index(['status','available_at']);$t->index(['status','leased_until']);});
Schema::create('hr_safety_register_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('register_type',30);$t->uuid('register_id');$t->string('event_type',60);$t->string('from_status',30)->nullable();$t->string('to_status',30)->nullable();$t->json('safe_details')->nullable();$t->char('event_checksum',64);$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestampTz('occurred_at');$t->index(['company_id','register_type','register_id','occurred_at'],'hr_safety_register_events_lookup');});
}public function down():void{Schema::dropIfExists('hr_safety_register_events');Schema::dropIfExists('hr_safety_external_notifications');Schema::table('hr_safety_actions',fn(Blueprint$t)=>$t->dropConstrainedForeignId('inspection_id'));Schema::dropIfExists('hr_safety_inspections');Schema::table('hr_relation_hearings',function(Blueprint$t){$t->dropConstrainedForeignId('chair_staff_id');$t->dropConstrainedForeignId('completed_by');$t->dropColumn(['attendee_snapshot','completed_at']);});Schema::dropIfExists('hr_relation_case_outcomes');Schema::dropIfExists('hr_relation_conflicts');}};
