<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('hr_expense_policy_versions',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('code',80);$t->unsignedInteger('version');$t->string('status',30)->default('pending_approval');$t->json('rules');$t->date('effective_from');$t->date('effective_until')->nullable();$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->foreignUuid('approved_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['company_id','code','version']);});
Schema::table('hr_expense_claims',function(Blueprint$t){$t->foreignUuid('policy_version_id')->nullable()->after('staff_id')->constrained('hr_expense_policy_versions')->restrictOnDelete();$t->text('decision_reason')->nullable();});
Schema::create('hr_expense_claim_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('claim_id')->constrained('hr_expense_claims')->restrictOnDelete();$t->string('event_type',60);$t->string('from_status',30)->nullable();$t->string('to_status',30)->nullable();$t->json('evidence')->nullable();$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('occurred_at');$t->index(['claim_id','occurred_at']);});
Schema::create('hr_accounting_outbox',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained('companies')->restrictOnDelete();$t->string('event_type',80);$t->string('aggregate_type',80);$t->uuid('aggregate_id');$t->json('payload');$t->char('payload_checksum',64);$t->string('status',30)->default('pending');$t->unsignedInteger('attempts')->default(0);$t->timestamp('available_at');$t->timestamp('acknowledged_at')->nullable();$t->string('external_reference',160)->nullable();$t->text('last_error')->nullable();$t->timestamps();$t->unique(['event_type','aggregate_type','aggregate_id']);});
Schema::create('hr_service_request_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('service_request_id')->constrained('hr_service_requests')->restrictOnDelete();$t->string('event_type',60);$t->string('from_status',30)->nullable();$t->string('to_status',30)->nullable();$t->text('encrypted_note')->nullable();$t->foreignUuid('actor_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('occurred_at');$t->index(['service_request_id','occurred_at']);});
Schema::create('hr_knowledge_acknowledgements',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('article_id')->constrained('hr_knowledge_articles')->restrictOnDelete();$t->foreignUuid('staff_id')->constrained('staff')->restrictOnDelete();$t->timestamp('acknowledged_at');$t->char('article_checksum',64);$t->unique(['article_id','staff_id']);});
}public function down():void{foreach(['hr_knowledge_acknowledgements','hr_service_request_events','hr_accounting_outbox','hr_expense_claim_events']as$table)Schema::dropIfExists($table);Schema::table('hr_expense_claims',function(Blueprint$t){$t->dropConstrainedForeignId('policy_version_id');$t->dropColumn('decision_reason');});Schema::dropIfExists('hr_expense_policy_versions');}};
