<?php

$field = fn (string $key, string $label, string $type = 'text', array $rules = []) => [
    'key' => $key, 'label' => $label, 'type' => $type, 'required' => true, ...$rules,
];
$decision = fn (string $key, string $module, string $label, string $description, string $risk, array $fields, array $dependsOn = [], string $editor = 'Company administrator', string $approver = 'Independent company approver') => [
    'key' => $key, 'module' => $module, 'label' => $label, 'description' => $description,
    'risk' => $risk, 'depends_on' => $dependsOn, 'editor_role' => $editor, 'approver_role' => $approver,
    'field_schema' => $fields, 'initial_template' => [],
];

return [
    $decision('company.localization', 'company', 'Currency and timezone', 'Company display preferences; timestamps remain stored in UTC and are localized only for presentation.', 'operational', [$field('currency', 'Currency code', 'text', ['pattern' => '/^[A-Z]{3}$/']), $field('timezone', 'IANA timezone', 'timezone')]),
    $decision('hr.employee_numbering', 'hr', 'Employee numbering', 'Approved employee-number format, ownership and exception policy reference.', 'hr', [$field('policy_reference', 'Approved numbering policy reference')], ['company.localization']),
    $decision('hr.work_calendars', 'hr', 'Work calendars and locations', 'Approved calendar, holiday, location and work-pattern source reference.', 'hr', [$field('policy_reference', 'Approved calendar and location policy reference')], ['company.localization']),
    $decision('hr.retention_privacy', 'hr', 'Employee retention and privacy', 'Approved retention, legal-hold and confidentiality policy reference.', 'privacy', [$field('policy_reference', 'Approved retention and privacy policy reference')], ['company.localization'], 'Company privacy administrator', 'Independent privacy approver'),
    $decision('device.biometric_privacy', 'devices', 'Biometric privacy basis', 'Approved purpose, notice, lawful basis, retention and access-control reference.', 'privacy', [$field('policy_reference', 'Approved biometric privacy decision reference')], ['hr.retention_privacy'], 'Company privacy administrator', 'Independent privacy and security approvers'),
    $decision('device.integration', 'devices', 'Attendance device integration', 'Approved provider topology and verified model/firmware evidence.', 'security', [$field('topology', 'Topology', 'select', ['options' => ['direct_isapi', 'hikcentral', 'push_sdk', 'csv', 'hybrid']]), $field('evidence_reference', 'Verified provider, model and firmware evidence')], ['company.localization', 'device.biometric_privacy'], 'Company integration administrator', 'Independent platform security approver'),
    $decision('employment.driver_relationship', 'hr', 'Driver employment relationship', 'Approved employee, contractor, or mixed relationship and mapping rule.', 'hr', [$field('relationship', 'Relationship', 'select', ['options' => ['employee', 'contractor', 'mixed']]), $field('policy_reference', 'Approved mapping and review policy reference')], ['hr.employee_numbering']),
    $decision('hr.attendance_policy', 'hr', 'Attendance policy', 'Approved attendance, correction and payable-fact governance reference.', 'hr', [$field('policy_reference', 'Approved attendance policy reference')], ['hr.work_calendars', 'device.integration']),
    $decision('hr.leave_overtime_policy', 'hr', 'Leave and overtime policy', 'Approved leave, overtime, rounding and exception policy reference.', 'hr', [$field('policy_reference', 'Approved leave and overtime policy reference')], ['hr.work_calendars']),
    $decision('hr.payroll_calendar_policy', 'payroll', 'Payroll calendar policy', 'Approved pay frequency, cutoff and period calendar reference without invented values.', 'financial', [$field('policy_reference', 'Approved payroll calendar policy reference')], ['hr.work_calendars', 'employment.driver_relationship'], 'Company payroll administrator', 'Independent HR and Finance approvers'),
    $decision('hr.document_governance', 'hr', 'Document governance', 'Approved document type, access, retention and signature policy reference.', 'privacy', [$field('policy_reference', 'Approved document governance reference')], ['hr.retention_privacy'], 'Company HR administrator', 'Independent privacy approver'),
    $decision('hr.approval_access', 'hr', 'Approval and access model', 'Approved delegation, segregation-of-duties and emergency-access reference.', 'security', [$field('policy_reference', 'Approved access and approval model reference')], ['hr.employee_numbering'], 'Company security administrator', 'Independent security approver'),
    $decision('hr.notification_policy', 'hr', 'Notification policy', 'Approved audience, channel, confidentiality and escalation reference.', 'privacy', [$field('policy_reference', 'Approved notification policy reference')], ['hr.approval_access', 'hr.retention_privacy']),
    $decision('hr.migration_scope', 'hr', 'Migration and opening balances', 'Approved sources, cutover, rejected-row ownership and reconciliation reference.', 'migration', [$field('policy_reference', 'Approved migration and reconciliation reference')], ['hr.employee_numbering', 'hr.document_governance', 'hr.approval_access'], 'Company migration administrator', 'Independent business owner'),
    $decision('sales.commission_policy', 'sales', 'Sales commission policy', 'Approved plan, cycle and activation reference; no financial values are invented.', 'financial', [$field('plan_reference', 'Approved plan reference'), $field('cycle_reference', 'Approved cycle reference'), $field('activation_date', 'Activation date', 'date')], ['company.localization', 'hr.approval_access'], 'Company Sales administrator', 'Independent Sales and Finance approvers'),
    $decision('payroll.statutory', 'payroll', 'Payroll and statutory basis', 'Qualified-adviser and approved statutory policy references; no statutory values are invented.', 'statutory', [$field('adviser_reference', 'Qualified adviser approval'), $field('policy_reference', 'Approved statutory policy')], ['hr.payroll_calendar_policy', 'hr.retention_privacy'], 'Company payroll administrator', 'Independent qualified and Finance approvers'),
    $decision('integrations.approved_scope', 'integrations', 'Approved integration scope', 'Approved providers, purposes, data boundaries, credentials ownership and disablement reference.', 'security', [$field('policy_reference', 'Approved integration scope reference')], ['hr.approval_access', 'hr.notification_policy'], 'Company integration administrator', 'Independent platform security approver'),
];
